/**
 * Story hero image fallback mapping.
 *
 * Primary images come from Supabase Storage (story.image_url).
 * These category-based images serve as quick-loading static fallbacks
 * when the database image hasn't loaded yet.
 *
 * Images are stored in static/images/category-{slug}.{jpg,webp}
 * generated by scripts/generate_fallback_images.py
 */

const categoryImageMap: Record<string, string> = {
	klima: 'category-klima',
	gesundheit: 'category-gesundheit',
	wissenschaft: 'category-wissenschaft',
	gemeinschaft: 'category-gemeinschaft',
	tiere: 'category-tiere',
	kultur: 'category-kultur',
	innovation: 'category-innovation'
};

const DEFAULT_FALLBACK = 'category-gemeinschaft';

/**
 * Get the hero image source for a story.
 *
 * Priority:
 *   1. Supabase image_url (handled by the image loader in the component)
 *   2. Category-appropriate static fallback image
 */
export function getStoryHeroImageSrc(
	category: string | null | undefined,
	basePath: string,
	format: 'jpg' | 'webp' = 'jpg'
): string {
	const slug = categoryImageMap[category ?? ''] ?? DEFAULT_FALLBACK;
	return `${basePath}/images/${slug}.${format}`;
}

export function getDefaultHeroImageSrc(basePath: string, format: 'jpg' | 'webp' = 'jpg'): string {
	return `${basePath}/images/${DEFAULT_FALLBACK}.${format}`;
}
