import { getStoryBySlug } from '$lib/server/queries';
import type { RequestHandler } from './$types';

/**
 * OG-Image API endpoint — serves pre-rendered editorial PNG or falls back to SVG.
 *
 * URL: /api/og/[slug]
 *
 * Priority:
 *   1. If story has og_image_url (pre-rendered 1200x630 PNG), redirect to it.
 *      This is the preferred path — static PNGs are generated by the
 *      generate-og-images GitHub workflow and cached permanently.
 *   2. Otherwise, generate SVG on-the-fly (backward compatibility).
 *
 * SVG layout: Full-bleed story image + gradient overlay with
 * centered headline + 60px bottom brand bar with category and "NurEine".
 * Dimensions: 1200x630 (1.91:1) — optimal for WhatsApp, Twitter, Facebook, LinkedIn.
 */

// Category -> tone -> accent color
const toneColors: Record<string, string> = {
	amber: '#c87340',
	sage: '#5a7a52',
	rose: '#b87a7a',
	sky: '#6c8aa8'
};

const categoryTone: Record<string, string> = {
	klima: 'sage',
	gesundheit: 'rose',
	wissenschaft: 'sky',
	gemeinschaft: 'amber',
	tiere: 'sage',
	kultur: 'amber',
	innovation: 'sky'
};

function escapeXml(s: string): string {
	return s
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&apos;');
}

/** Wrap title text into SVG <tspan> elements for two-line display */
function wrapTitleSvg(title: string, maxChars: number): string[] {
	// Simple character-based wrapping (SVG text measurement isn't available at build time)
	if (title.length <= maxChars) return [escapeXml(title)];

	const words = title.split(' ');
	const lines: string[] = [];
	let current = '';

	for (const word of words) {
		const test = current ? `${current} ${word}` : word;
		if (test.length > maxChars && current) {
			lines.push(current);
			current = word;
		} else {
			current = test;
		}
	}
	if (current) lines.push(current);
	if (lines.length === 0) lines.push(escapeXml(title));

	return lines.map(escapeXml);
}

export const GET: RequestHandler = async ({ params, setHeaders }) => {
	const slug = params.slug;
	const story = await getStoryBySlug(slug);

	if (!story) {
		return new Response('Story not found', { status: 404 });
	}

	// Redirect to pre-rendered editorial PNG if available
	if (story.ogImageUrl) {
		return new Response(null, {
			status: 302,
			headers: {
				Location: story.ogImageUrl,
				'Cache-Control': 'public, max-age=3600, s-maxage=86400'
			}
		});
	}

	const tone = categoryTone[story.category] || 'amber';
	const accent = toneColors[tone];
	const imageUrl = story.image_url || story.imageUrl || '';

	const categoryLabel =
		{ klima: 'Klima', gesundheit: 'Gesundheit', wissenschaft: 'Wissenschaft', gemeinschaft: 'Gemeinschaft', tiere: 'Tiere', kultur: 'Kultur', innovation: 'Innovation' }[
			story.category
		] || story.category;

	// Build the SVG — full-bleed image + gradient overlay + headline + bottom brand bar
	const W = 1200;
	const H = 630;
	const BAR_HEIGHT = 60;
	const BAR_Y = H - BAR_HEIGHT;
	const BAR_PX = 48;
	const GRAD_H = 140;
	const GRAD_Y = H - GRAD_H;
	const HEADLINE_Y = BAR_Y - 56;

	const svgParts: string[] = [];

	// Canvas background
	svgParts.push(`<rect width="${W}" height="${H}" fill="#f5f1ea"/>`);

	// Defs: gradients
	svgParts.push(`<defs>
		<linearGradient id="barGrad" x1="0" y1="0" x2="0" y2="1">
			<stop offset="0%" stop-color="#1a1815" stop-opacity="0"/>
			<stop offset="100%" stop-color="#1a1815" stop-opacity="0.70"/>
		</linearGradient>
		<linearGradient id="gradientOverlay" x1="0" y1="0" x2="0" y2="1">
			<stop offset="0%" stop-color="#1a1815" stop-opacity="0"/>
			<stop offset="100%" stop-color="#1a1815" stop-opacity="0.62"/>
		</linearGradient>
		<linearGradient id="accentLine" x1="0" y1="0" x2="1" y2="0">
			<stop offset="0%" stop-color="${accent}" stop-opacity="0"/>
			<stop offset="30%" stop-color="${accent}" stop-opacity="0.30"/>
			<stop offset="70%" stop-color="${accent}" stop-opacity="0.30"/>
			<stop offset="100%" stop-color="${accent}" stop-opacity="0"/>
		</linearGradient>
	</defs>`);

	// Story image (full-bleed, object-fit: cover equivalent)
	if (imageUrl && imageUrl.startsWith('http')) {
		const escapedImageUrl = escapeXml(imageUrl);
		svgParts.push(`<image href="${escapedImageUrl}" x="0" y="0" width="${W}" height="${H}" preserveAspectRatio="xMidYMid slice"/>`);
	} else {
		// Fallback: accent-tinted background
		svgParts.push(`<rect width="${W}" height="${H}" fill="${accent}" fill-opacity="0.05"/>`);
	}

	// Gradient overlay (bottom 140px)
	svgParts.push(`<rect x="0" y="${GRAD_Y}" width="${W}" height="${GRAD_H}" fill="url(#gradientOverlay)"/>`);

	// Headline text — centered in gradient zone
	const title = story.title || '';
	const titleLines = wrapTitleSvg(title, 55);
	const lineHeight = 34;
	const totalTextH = titleLines.length * lineHeight;
	const textStartY = HEADLINE_Y - totalTextH / 2 + lineHeight - 6;

	svgParts.push(`<text x="${W / 2}" y="${textStartY}" text-anchor="middle" font-family="Fraunces, Cambria, Georgia, serif" font-size="28" font-weight="500" fill="#f5f1ea" letter-spacing="-0.02em">`);
	for (let i = 0; i < titleLines.length; i++) {
		const dy = i === 0 ? 0 : lineHeight;
		svgParts.push(`<tspan x="${W / 2}" dy="${dy}">${titleLines[i]}</tspan>`);
	}
	svgParts.push(`</text>`);

	// Bottom bar gradient
	svgParts.push(`<rect x="0" y="${BAR_Y}" width="${W}" height="${BAR_HEIGHT}" fill="url(#barGrad)"/>`);

	// Accent line at top of bar
	svgParts.push(`<line x1="${BAR_PX}" y1="${BAR_Y}" x2="${W - BAR_PX}" y2="${BAR_Y}" stroke="url(#accentLine)" stroke-width="1"/>`);

	// Category dot (left)
	const dotR = 4;
	const dotCx = BAR_PX;
	const dotCy = BAR_Y + BAR_HEIGHT / 2;
	svgParts.push(`<circle cx="${dotCx}" cy="${dotCy}" r="${dotR}" fill="${accent}"/>`);

	// Category label (left of bar)
	const catX = dotCx + dotR + 12;
	const catTextY = BAR_Y + BAR_HEIGHT / 2 + 7;
	svgParts.push(`<text x="${catX}" y="${catTextY}" font-family="Fraunces, Cambria, Georgia, serif" font-size="20" font-weight="500" fill="#f5f1ea" letter-spacing="0.08em">${categoryLabel.toUpperCase()}</text>`);

	// Brand name (right of bar)
	const brandX = W - BAR_PX;
	const brandTextY = BAR_Y + BAR_HEIGHT / 2 + 5;
	svgParts.push(`<text x="${brandX}" y="${brandTextY}" text-anchor="end" font-family="Fraunces, Cambria, Georgia, serif" font-size="16" fill="#9a9087">NurEine</text>`);

	const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${svgParts.join('')}</svg>`;

	setHeaders({
		'Content-Type': 'image/svg+xml',
		'Cache-Control': 'public, max-age=3600, s-maxage=86400',
		'CDN-Cache-Control': 'public, max-age=86400'
	});

	return new Response(svg, {
		headers: { 'Content-Type': 'image/svg+xml' }
	});
};
