-- Migration 00007: Add og_image_url column for pre-rendered OG images
--
-- Stores the public URL of a 1200x630 editorial PNG Open Graph image
-- (generated by scripts/generate_og_images.py via Pillow)
-- for WhatsApp, Twitter, Facebook, etc. link previews.

ALTER TABLE nureine_stories
  ADD COLUMN IF NOT EXISTS og_image_url TEXT;

COMMENT ON COLUMN nureine_stories.og_image_url IS
  'Public URL to pre-rendered 1200x630 editorial OG image (PNG) in Supabase Storage bucket og_images';

-- Storage bucket: og_images (Public)
-- Must be created via Supabase Dashboard or Management API:
--   - Bucket name: og_images
--   - Public bucket: yes
--   - Required policies:
--       SELECT — public (for link previews)
--       INSERT — service_role (for the OG generation pipeline)
