-- Migration 00016: Add og_image_srcset for responsive OG image variants
--
-- Stores metadata about OG image variants (1x/2x in PNG/WebP/AVIF formats)
-- generated by the updated generate_og_images.py script.
--
-- Structure:
-- {
--   "png_1x": "https://...",
--   "png_2x": "https://...",
--   "webp_1x": "https://...",
--   "webp_2x": "https://...",
--   "avif_1x": "https://... or null",
--   "avif_2x": "https://... or null"
-- }
--
-- This enables responsive images via srcset for better performance:
-- - WebP for modern browsers (~60% smaller than PNG)
-- - AVIF for cutting-edge browsers (~30% smaller than WebP)
-- - 2x variants for high-DPI displays (retina)

ALTER TABLE nureine_stories
  ADD COLUMN IF NOT EXISTS og_image_srcset JSONB;

COMMENT ON COLUMN nureine_stories.og_image_srcset IS
  'Metadata about OG image variants (1x/2x in PNG/WebP/AVIF). Used by frontend for responsive <img> srcset';

-- Create index for faster queries if filtering by variant availability
CREATE INDEX IF NOT EXISTS idx_nur_stories_og_image_srcset
  ON nureine_stories USING GIN (og_image_srcset);
