-- NurEine Fetch (Spool-Modus, Supabase-402) 20260719-033438
-- Idempotenter Import (WHERE NOT EXISTS auf source_url). Bilder fehlen (Storage gesperrt).

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Alzheimer-Wirkstoff repariert im Labor das Erbgut von Nervenzellen', 'Ein bereits sicher getesteter Wirkstoff bremste im Krankheitsmodell gleich mehrere Alzheimer-Merkmale zugleich.', 'Bei der Alzheimer-Krankheit lagern sich im Gehirn giftige Eiweiße ab – vor allem sogenanntes Amyloid-beta und Tau, zwei Proteine, die verklumpen und die Verbindungen zwischen den Nervenzellen zerstören. Die meisten bisherigen Medikamente zielen nur auf eines dieser Probleme.

Ein Team des King''s College London verfolgt einen anderen Weg: Es hat einen Ansatz entwickelt, der über ein einziges Schlüssel-Protein mehrere Krankheitsmerkmale zugleich angeht. Der eingesetzte Wirkstoff heißt KCL-286.

Das Bemerkenswerte daran: Dieser Stoff wurde ursprünglich für die Behandlung von Rückenmarksverletzungen entwickelt und hat bereits eine sogenannte Phase-1-Studie durchlaufen – den ersten Test am Menschen, bei dem geprüft wird, ob ein Mittel sicher und verträglich ist. Diese Hürde gilt als genommen.

In einem Labormodell der Krankheit reduzierte KCL-286 mehrere der typischen, mit Alzheimer verbundenen Veränderungen. Das ist noch kein Beweis, dass er auch bei Patientinnen und Patienten wirkt – Labormodelle sind ein früher Schritt.

Warum die Nachricht dennoch zählt: Weil der Wirkstoff bereits als sicher eingestuft ist, könnte eine Erprobung an Erkrankten schneller beginnen als bei einer komplett neuen Substanz, die erst jahrelange Sicherheitstests durchlaufen müsste.

Alzheimer ist die häufigste Form der Demenz und betrifft weltweit viele Millionen Menschen und ihre Angehörigen. Jeder ernstzunehmende neue Ansatzpunkt ist deshalb eine Nachricht wert – mit der nötigen Vorsicht, dass der Weg von der Laborbank bis zur Zulassung lang und ungewiss bleibt.', 'Bei Alzheimer verklumpen im Gehirn giftige Eiweiße und schädigen nach und nach die Nervenzellen – bisher gibt es kaum ein Mittel, das an mehreren Ursachen gleichzeitig ansetzt. Forschende des King''s College London zeigten nun, dass der Wirkstoff KCL-286, der die erste Sicherheitsprüfung am Menschen bereits bestanden hat, in einem Labormodell viele dieser Krankheitsmerkmale abmildert. Weil der Stoff schon als sicher gilt, könnte der Weg zu einer Erprobung an Patienten deutlich kürzer sein als bei einem völlig neuen Medikament. Noch ist es kein fertiges Mittel, aber ein ungewöhnlich weit fortgeschrittener Ansatzpunkt gegen eine Krankheit, für die es bislang wenig Hoffnung gab.', 'gesundheit', 'Vereinigtes Königreich', 'GB', 51.5, -0.12, NULL, 'https://www.goodnewsnetwork.org/drug-may-repair-dna-at-earliest-stages-of-alzheimers-and-its-already-passed-safety-trials/', 'Good News Network', 1000000, 70, 70, 58, 1, '2026-07-18T16:51:00+00:00', 12, 'Alzheimer ist eine Krankheit, bei der das Gehirn im Alter das Erinnern verlernt.', 'Warum ist es hilfreich, wenn ein Medikament schon für etwas anderes sicher getestet wurde?', 'hope', 70, false, NULL, true, NULL, 'Das hat mich heute leiser hoffen lassen:', NULL, NULL, false, 70, 'Ein bereits sicher getesteter Wirkstoff verkürzt womöglich den Weg zu einer echten Alzheimer-Therapie.', 'Ein Mittel, das eigentlich für Rückenmarksverletzungen gedacht war, bremst im Labor gleich mehrere Alzheimer-Ursachen – und gilt schon als sicher.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/drug-may-repair-dna-at-earliest-stages-of-alzheimers-and-its-already-passed-safety-trials/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'China und Russland setzen fast 500.000 junge Störe im Amur aus', 'Der einst leergefischte Grenzfluss bekommt Nachwuchs: gemeinsame Aussetzaktion für den fast verschwundenen Riesenstör.', 'Als die BBC 2008 in die frostige nordostchinesische Provinz Heilongjiang reiste, um einen Blick auf die berühmten Riesenstöre des Flusses zu erhaschen, mussten die Dokumentarfilmer feststellen: Es gab keine mehr. Der Fluss – auf Chinesisch Heilongjiang, „Schwarzer-Drachen-Fluss“, auf Russisch Amur – war chronisch überfischt.

Doch mit Chinas wirtschaftlichem Aufstieg wuchs auch die Sorge um die Umwelt, und dem Schutz des Heilongjiang-Störs wurde besondere Aufmerksamkeit gewidmet. China teilt sich den Fluss mit Russland.

Umweltbehörden beider Länder kamen kürzlich in der Stadt Tongjiang zusammen, um gemeinsam große Mengen junger Fische im Fluss auszusetzen – nach Angaben der beteiligten Stellen hunderttausende, in der Summe bis in den Millionenbereich reichende Jungtiere.

Störe sind ein Sinnbild für die Verletzlichkeit alter Fischarten: Sie werden sehr alt und pflanzen sich erst spät fort, weshalb sich Überfischung besonders lange auswirkt. Genau deshalb sind Besatzaktionen wie diese so wichtig – sie geben dem Bestand über Jahre die Chance, sich wieder aufzubauen.

Bemerkenswert ist auch das Signal: Zwei Nachbarländer koordinieren sich, um eine gemeinsame Lebensgrundlage zu schützen. Artenschutz endet nicht an einer Grenze – ein Fluss und seine Fische kennen keine Landkarten.', 'Der Amur, ein großer Grenzfluss zwischen China und Russland, galt lange als chronisch überfischt – der berühmte Riesenstör war dort praktisch verschwunden. Umweltbehörden beider Länder haben nun gemeinsam hunderttausende junge Störe in den Fluss entlassen, um den Bestand wieder aufzubauen. Solche Besatzaktionen geben einer bedrohten, sehr langlebigen Fischart die Chance, sich über Jahre erneut zu vermehren. Dass zwei Nachbarländer dafür zusammenarbeiten, zeigt, dass Artenschutz auch über Grenzen hinweg funktionieren kann.', 'tiere', 'China', 'CN', 47.6, 132.5, NULL, 'https://www.goodnewsnetwork.org/chinese-russian-biologists-release-nearly-500000-young-sturgeon-into-the-amur-river/', 'Good News Network', 50000, 75, 65, 55, 1, '2026-07-17T11:00:54+00:00', 8, 'Ein Stör ist ein sehr großer, sehr alter Fisch, den es kaum noch gibt.', 'Warum ist es gut, wenn zwei Länder sich um denselben Fluss kümmern?', 'hope', 45, false, NULL, true, NULL, 'krass, dass ausgerechnet die zwei sowas zusammen machen:', NULL, NULL, false, 40, 'Eine fast verschwundene, uralte Fischart bekommt über Ländergrenzen hinweg eine zweite Chance.', 'Ein Fluss zwischen China und Russland war leergefischt – jetzt setzen beide Länder gemeinsam hunderttausende junge Störe wieder aus.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/chinese-russian-biologists-release-nearly-500000-young-sturgeon-into-the-amur-river/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Indien bringt seinen ersten Hochgeschwindigkeitszug an den Start', 'Die Verbindung Mumbai–Ahmedabad soll die Fahrzeit um über vier Stunden verkürzen.', 'Für das nach Fahrgastzahlen am stärksten genutzte Bahnsystem der Welt rückt ein Meilenstein näher: der erste Hochgeschwindigkeitszug – im Volksmund „Bullet Train“ – Indiens.

Der phasenweise Passagierbetrieb soll ab dem 15. August 2027 beginnen, sofern es keine weiteren Verzögerungen gibt. Die Strecke verbindet die Finanzmetropole Mumbai mit Ahmedabad im westlichen Bundesstaat Gujarat.

Der Zug im japanischen Shinkansen-Stil – benannt nach den japanischen Schnellzügen, die als Vorbild dienten – soll die Fahrzeit um mehr als vier Stunden verkürzen. Auch Surat, das globale Zentrum der Diamantschleiferei, liegt an der Linie.

Das Projekt ist seit Langem in Arbeit und entstand in enger Zusammenarbeit mit Japan, das technisches Wissen und Finanzierung beisteuerte.

Warum das mehr ist als ein Prestigeprojekt: Schnelle Bahnverbindungen sparen Millionen Reisenden Zeit und können Kurzstreckenflüge ersetzen, die deutlich mehr klimaschädliches Treibhausgas ausstoßen. Wenn eine Strecke zwischen zwei Wirtschaftszentren zuverlässig und schnell wird, verändert das, wie ein ganzes Land sich bewegt.

Für ein Land mit über einer Milliarde Menschen ist der Einstieg in die Hochgeschwindigkeitsbahn ein Infrastruktur-Sprung, dessen Wirkung sich über Jahrzehnte entfalten kann.', 'Indien hat eines der am stärksten genutzten Bahnnetze der Welt, aber bislang keinen Hochgeschwindigkeitszug. Das ändert sich: Die erste „Bullet-Train“-Strecke zwischen der Finanzmetropole Mumbai und der Stadt Ahmedabad steht kurz vor dem Betrieb und soll die Reisezeit um mehr als vier Stunden verkürzen. Schnelle, klimafreundlichere Bahnverbindungen können Millionen Menschen Zeit sparen und Flüge auf der Strecke überflüssig machen. Für ein Land mit über einer Milliarde Einwohnern ist das ein Infrastruktur-Sprung mit großer Reichweite.', 'innovation', 'Indien', 'IN', 19.08, 72.88, NULL, 'https://www.goodnewsnetwork.org/japanese-engineering-helping-india-modernize-massive-railway-system-starting-with-her-first-bullet-train/', 'Good News Network', 5000000, 90, 70, 64, 1, '2026-07-16T15:30:21+00:00', 8, 'Ein Hochgeschwindigkeitszug fährt so schnell, dass eine lange Reise plötzlich kurz wird.', 'Was würdest du mit vier gesparten Stunden auf einer Reise machen?', 'hope', 40, false, NULL, true, NULL, 'les go – Indien steigt in die Schnellbahn ein:', NULL, NULL, false, 75, 'Millionen Reisende sparen bald Stunden – und schnelle Bahn kann klimaschädliche Kurzflüge ersetzen.', 'Indien hat das meistgenutzte Bahnnetz der Welt – und bekommt jetzt seinen allerersten Hochgeschwindigkeitszug.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/japanese-engineering-helping-india-modernize-massive-railway-system-starting-with-her-first-bullet-train/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Nach Damm-Rückbau: 20 Millionen Fische ziehen durch Maines Flüsse', 'Der höchste Bestand seit Jahrzehnten – weil mehrere große Staudämme abgerissen wurden.', 'Ein beliebter heimischer Fisch, dessen Fang bis 2012 verboten war, hat in Maines Flüssen ein bemerkenswertes Comeback erlebt – ausgelöst durch den Rückbau mehrerer großer Staudämme.

Staudämme sind für Wanderfische ein Problem: Sie versperren den Weg flussaufwärts zu den Laichplätzen. Für den Alewife, einen kleinen Flussheringsverwandten, bedeutete das seit dem 18. Jahrhundert einen stetigen Rückgang.

Besonders am Penobscot River hat die Entfernung von zwei Dämmen zu dem geführt, was Fachleute die „herausragende Erfolgsgeschichte unserer Zeit“ nennen. In diesem Jahr zählten Beobachter über 20 Millionen Flussheringe während der jährlichen Wanderung – der höchste Wert seit Jahrzehnten.

Wenn der Zug seinen Höhepunkt erreicht, wirkt er wie eine Naturgewalt: Ein sonst ruhiges Bachbett verwandelt sich von Ufer zu Ufer in einen silbernen Strom, wenn die Fische flussaufwärts ziehen, um zu laichen – ähnlich wie Lachse es tun.

Von diesem Reichtum lebten früher Siedler, indigene Gemeinschaften, Fischer und praktisch jeder Räuber im Wald. Mit den Fischen kehrt also ein ganzes Nahrungsnetz zurück.

Die Lehre ist einfach und ermutigend: Nimmt man einem Fluss die Barrieren, findet das Leben oft schneller zurück, als man erwartet.', 'Staudämme blockieren Flüsse und schneiden Wanderfische von ihren Laichplätzen ab – über Jahrzehnte kann das eine ganze Fischart fast auslöschen. Im US-Bundesstaat Maine wurden mehrere große Dämme entfernt, vor allem am Penobscot River. Das Ergebnis: über 20 Millionen wandernde Flussheringe wurden gezählt – der höchste Stand seit Jahrzehnten für einen Fisch, dessen Fang bis 2012 sogar verboten war. Die Rückkehr zeigt, wie schnell sich ein Fluss erholen kann, wenn man ihm die Barrieren wegnimmt.', 'tiere', 'Vereinigte Staaten', 'US', 44.8, -68.77, NULL, 'https://www.goodnewsnetwork.org/maine-counts-over-20-million-river-herring-during-annual-run-the-highest-in-decades/', 'Good News Network', 100000, 85, 80, 66, 1, '2026-07-16T11:00:40+00:00', 8, 'Ein Staudamm ist eine Mauer im Fluss – für Fische ist sie wie eine verschlossene Tür.', 'Was passiert wohl noch alles, wenn ein Fluss wieder frei fließen darf?', 'wonder', 45, false, NULL, true, NULL, 'krass wie schnell sich das erholt hat:', NULL, NULL, false, 45, 'Reißt man Staudämme ab, kehren die Fische zurück – ein ganzes Flussleben erholt sich messbar.', 'Man riss ein paar Staudämme ab – und plötzlich zogen 20 Millionen Fische durch den Fluss, so viele wie seit Jahrzehnten nicht.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/maine-counts-over-20-million-river-herring-during-annual-run-the-highest-in-decades/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Brasiliens Buckelwale: Bestand seit Ende des Walfangs 27-mal größer', 'Von 2.000 auf rund 35.000 Tiere – vor Rio kehren die Wale zurück.', 'Die Zahl der Buckelwale steigt weltweit weiter an – und mit ihr die Rekorde bei den Sichtungen in einzelnen Beobachtungssaisons.

In Brasiliens bekannter Guanabara-Bucht werden Wal-Beobachtungsfahrten immer beliebter. Grund ist die wachsende Population der Buckelwale: von rund 2.000 Tieren im Jahr 1986 auf heute etwa 35.000. Das ist mehr als das 27-Fache.

Jedes Jahr wandern die gewaltigen Meeressäuger von ihren Futtergründen in der Antarktis in wärmere Gewässer, um sich fortzupflanzen. Die Population, die an Guanabara und Rio de Janeiro vorbeizieht, steuert auf die Abrolhos-Bank zu – ein Korallenriff-Gebiet vor den Küsten der brasilianischen Bundesstaaten Bahia und Espírito Santo und eines der artenreichsten Gebiete des Atlantiks.

Die Wanderung findet zwischen Juni und November statt und macht die Region zu einem Fenster in eine Erholung, die vor wenigen Jahrzehnten kaum denkbar war.

Der Grund für die Rückkehr ist unspektakulär und gerade deshalb so ermutigend: Seit der kommerzielle Walfang beendet wurde, konnten sich die Bestände über Jahrzehnte wieder aufbauen. Buckelwale bekommen selten Nachwuchs und wachsen langsam – umso deutlicher zeigt die Zahl, was Geduld und Schutz bewirken.', 'Buckelwale wurden durch den kommerziellen Walfang an vielen Küsten fast ausgerottet. Vor Brasilien zeigt sich nun, wie kraftvoll sich die Bestände erholen, seit der Walfang beendet wurde: In der Bucht von Guanabara bei Rio de Janeiro stieg die Zahl der Buckelwale von rund 2.000 im Jahr 1986 auf etwa 35.000 heute. Immer mehr Menschen können die riesigen Meeressäuger auf ihrer jährlichen Wanderung beobachten. Es ist eines der eindrücklichsten Beispiele dafür, dass Schutzentscheidungen wirken – wenn man Tieren Zeit lässt.', 'tiere', 'Brasilien', 'BR', -22.8, -43.15, NULL, 'https://www.goodnewsnetwork.org/humpback-whale-watching-surges-in-brazil-where-population-has-grown-27-fold-since-whaling-ended/', 'Good News Network', 35000, 85, 75, 60, 1, '2026-07-15T18:30:48+00:00', 6, 'Buckelwale sind riesige Wale, die jedes Jahr weite Reisen durch das Meer machen.', 'Warum dauert es so lange, bis sich so große Tiere wieder erholen?', 'wonder', 45, false, NULL, true, NULL, '27-mal mehr Wale – nur weil man aufgehört hat:', NULL, NULL, false, 35, 'Seit der Walfang endete, hat sich ein fast ausgerotteter Bestand um das 27-Fache erholt.', 'Vor Brasilien gab es 1986 noch 2.000 Buckelwale. Heute sind es rund 35.000 – weil man aufhörte, sie zu jagen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/humpback-whale-watching-surges-in-brazil-where-population-has-grown-27-fold-since-whaling-ended/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'In Sierra Leone lernen Kriegsversehrte, sich selbst zu ernähren', 'Ein Programm bringt Menschen mit Amputationen nachhaltigen Ackerbau bei – und ein eigenes Einkommen.', 'Ein Landwirtschaftsprogramm in Sierra Leone hilft Menschen mit Amputationen, Fähigkeiten, Unabhängigkeit und ein eigenes Einkommen zu gewinnen.

Gegründet wurde die Initiative von Mambud Samai, einem Pastor, der zum Landwirt wurde. Sie bringt Menschen mit Gliedmaßenverlust bei, nachhaltig zu wirtschaften – so, dass viele ihr eigenes Essen anbauen und kleine kommerzielle Parzellen aufbauen können.

Samai selbst musste während des elf Jahre langen Bürgerkriegs aus dem Land fliehen. In diesem Konflikt erlitten viele Zivilistinnen und Zivilisten lebensverändernde Verletzungen. Schätzungen zufolge hinterließ der Krieg fast 30.000 Menschen mit Amputationen im ganzen Land – viele von ihnen warten bis heute auf echte Perspektiven.

Das Besondere an dem Ansatz: Er behandelt die Menschen nicht als Empfänger von Almosen, sondern als Landwirte in Ausbildung. Wer gelernt hat, den Boden zu bearbeiten, kann sich ernähren und darüber hinaus etwas verkaufen – das schafft Würde, nicht nur Versorgung.

So wird aus einer der bittersten Folgen eines Krieges ein Weg zurück in ein selbstbestimmtes Leben: Statt auf Hilfe zu warten, bauen die Teilnehmenden ihre eigene Zukunft an – im wörtlichen Sinne.', 'Im Bürgerkrieg in Sierra Leone verloren fast 30.000 Menschen Gliedmaßen; viele leben bis heute in Armut. Ein Programm des früheren Pastors und heutigen Landwirts Mambud Samai bringt Menschen mit Amputationen bei, nachhaltig Landwirtschaft zu betreiben. Viele können so eigenes Essen anbauen und kleine Handelsflächen aufbauen. Das gibt ihnen Fähigkeiten, Unabhängigkeit und einen Weg zu eigenem Einkommen – aus Betroffenen werden Menschen, die für sich selbst sorgen.', 'gemeinschaft', 'Sierra Leone', 'SL', 8.48, -13.23, NULL, 'https://www.positive.news/environment/agriculture/sierra-leone-programme-helps-amputees-rebuild-lives-in-sierra-leone/', 'Positive.News', 30000, 80, 70, 58, 1, '2026-07-16T11:45:01+00:00', 10, 'Eine Amputation heißt: Ein Mensch hat einen Arm oder ein Bein verloren.', 'Was ist der Unterschied zwischen jemandem helfen und jemandem beibringen, sich selbst zu helfen?', 'pride', 35, true, 'mensch', true, 'Ein Krieg nahm ihnen die Gliedmaßen. Ein Bauer gibt ihnen etwas zurück.', 'Manchmal lösen Menschen Probleme einfach. Leise.', '{"hook": "Fast 30.000 Menschen verloren im Krieg Arme oder Beine.", "aufloesung": "Ein Programm des Landwirts Mambud Samai bringt ihnen nachhaltigen Ackerbau bei. Viele bauen heute ihr eigenes Essen an und starten kleine Handelsflächen.", "stille": "Nicht Mitleid. Ein Feld, das ihnen gehört."}'::jsonb, 'Ein Krieg nahm fast 30.000 Menschen einen Arm oder ein Bein.
Was ein einzelner Bauer daraus gemacht hat, ist eine der stillen guten Nachrichten. 👇

Quelle: Positive.News', false, 40, 'Menschen, die im Krieg Gliedmaßen verloren, lernen, sich selbst zu ernähren – aus Betroffenen werden Bauern.', 'In Sierra Leone bringt ein Ex-Pastor Kriegsversehrten das Farmen bei – damit sie sich selbst ernähren statt zu betteln.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.positive.news/environment/agriculture/sierra-leone-programme-helps-amputees-rebuild-lives-in-sierra-leone/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Sozialbetrieb gibt Geflüchteten mit Kerzen den ersten Job', 'Neu Angekommene stellen nachhaltige Kerzen her – und bauen so Einkommen, Sprache und Arbeitsnachweis auf.', 'In den USA stellt ein Sozialunternehmen neu angekommene Geflüchtete ein, um nachhaltige Kerzen herzustellen – und hilft ihnen damit, Geld zu verdienen, Englisch zu üben und einen Arbeitsnachweis aufzubauen.

Als Maguno 2023 mit zwei ihrer erwachsenen Söhne in Olympia im US-Bundesstaat Washington ankam – nach der Flucht vor dem Krieg im Kongo und 30 Jahren in einem Flüchtlingslager in Tansania – begann sie nicht nur ein neues Leben. Eines der ersten Dinge, die sie tun wollte, war, das Reisedarlehen zurückzuzahlen, das ihre Familie in die USA gebracht hatte.

Wie viele in den USA neu angesiedelte Geflüchtete wurde von ihr erwartet, die Kosten dieser Flüge nach der Ankunft zurückzuzahlen. Für Maguno bedeutete das Tilgen der Schulden vor allem eines: Arbeit, Einkommen und den Beweis der Unabhängigkeit – in einem Land, in dem neu Angekommene oft ganz von vorn beginnen.

Genau hier setzt der Betrieb an. Kerzenherstellung ist ein Handwerk, das sich schnell erlernen lässt und keine perfekten Sprachkenntnisse voraussetzt. Wer mitarbeitet, verdient erstes eigenes Geld, übt nebenbei Englisch und – oft am wichtigsten – kann später einen Arbeitsnachweis vorlegen.

Der erste Job ist für viele Geflüchtete die schwerste Hürde: Ohne Referenzen bekommt man keine Arbeit, ohne Arbeit keine Referenzen. Ein Modell, das diesen Kreis durchbricht, ist mehr als ein netter Zuverdienst – es ist der erste Schritt in ein selbstbestimmtes Leben.', 'Wer als Geflüchteter in den USA ankommt, muss oft die Kosten des eigenen Fluges zurückzahlen – und braucht dafür zuerst Arbeit, die schwer zu finden ist. Ein Sozialunternehmen stellt neu Angekommene ein, um nachhaltige Kerzen zu fertigen. Dabei verdienen sie Geld, üben Englisch und sammeln einen ersten Arbeitsnachweis. So wird aus einem uralten Handwerk ein Sprungbrett in ein selbstständiges Leben. Der erste Job ist oft die schwerste Hürde – dieses Modell nimmt sie.', 'gemeinschaft', 'Vereinigte Staaten', 'US', 47.04, -122.9, NULL, 'https://www.positive.news/economics/social-enterprise/refugee-candlemakers-rebuilding-lives-through-work/', 'Positive.News', 5000, 70, 70, 55, 1, '2026-07-07T07:00:12+00:00', 10, 'Geflüchtete sind Menschen, die ihr Zuhause verlassen mussten, weil dort Krieg war.', 'Warum ist der allererste Job manchmal am schwersten zu bekommen?', 'hope', 45, true, 'mensch', true, 'Ohne Job keine Referenzen. Ohne Referenzen kein Job. Wie kommt man da raus?', 'fand ich einen richtig klugen Ansatz:', '{"hook": "Der erste Job ist für Geflüchtete oft die schwerste Hürde.", "aufloesung": "Ein Sozialbetrieb stellt neu Angekommene ein, um nachhaltige Kerzen zu machen. Sie verdienen erstes Geld, üben Englisch und bekommen einen Arbeitsnachweis.", "stille": "Ein Anfang, den ihnen sonst niemand gibt."}'::jsonb, 'Ohne Job keine Referenzen – ohne Referenzen kein Job.
Wie ein einfaches Handwerk diesen Kreis durchbricht, siehst du beim Wischen. 👇

Quelle: Positive.News', false, 25, 'Der erste Job ist für Geflüchtete die schwerste Hürde – ein Handwerk hilft ihnen, sie zu nehmen.', 'Ein Betrieb gibt geflüchteten Menschen ihren allerersten Job – mit Kerzen. Genau der Nachweis, den sonst keiner ihnen gibt.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.positive.news/economics/social-enterprise/refugee-candlemakers-rebuilding-lives-through-work/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Tampons werden zum medizinischen Diagnose-Werkzeug', 'Was jede Frau kennt, könnte künftig Krankheiten früh erkennen – ganz ohne Arztbesuch.', 'Manchmal entstehen die folgenreichsten Erfindungen aus Frust. Als Ridhi Tariyal Anfang dreißig war, bat sie ihre Frauenärztin um einen Fruchtbarkeitstest. Die Ärztin wies die Bitte ab – ein solcher Test sei nicht möglich.

Tariyal wusste es besser. Mit einem MBA von Harvard und einem Masterabschluss in biomedizinischem Unternehmertum vom MIT kannte sie das Anti-Müller-Hormon, einen etablierten Marker für die Eierstockreserve, also einen Anhaltspunkt dafür, wie viele Eizellen einer Frau noch zur Verfügung stehen. Der Test existierte. Dennoch wollte ihre Ärztin ihn nicht anordnen.

Die Erfahrung frustrierte sie so sehr, dass sie ihre eigene Gesundheit zum Forschungsprojekt machte. „Es gibt Tausende Frauen wie mich“, sagt Tariyal, heute 45. Frauen bekämen immer später Kinder, hätten aber kaum einfache Möglichkeiten, sich über ihren Zustand zu informieren.

Ihr Ansatz: Menstruationsblut, das bislang als bloßer Abfall behandelt wird, enthält eine Fülle medizinischer Informationen. Über den Tampon lässt sich dieses Blut gewinnen und auswerten – für Tests, die Frauen sonst nur mit ärztlicher Erlaubnis und im Labor bekommen.

Damit würde aus einem Alltagsprodukt ein niedrigschwelliges Diagnose-Werkzeug: unkompliziert, zu Hause, ohne das Gefühl, um jeden Test kämpfen zu müssen.

Die eigentliche gute Nachricht steckt hinter der Technik: Wenn Frauengesundheit ernst genommen wird, entstehen daraus konkrete medizinische Fortschritte, von denen sehr viele Menschen profitieren können.', 'Menstruationsblut enthält wertvolle medizinische Informationen, wurde aber lange als bloßer Abfall behandelt. Eine Forscherin mit Abschlüssen von Harvard und MIT entwickelt Verfahren, um über den Tampon genau dieses Blut für Diagnosen zu nutzen – etwa für Tests, die Frauen sonst mühsam beim Arzt erbitten müssen. So könnte ein alltägliches Produkt zu einem einfachen, würdevollen Frühwarnsystem für die Gesundheit werden. Es ist ein Beispiel dafür, wie das Ernstnehmen von Frauengesundheit neue Medizin hervorbringt.', 'gesundheit', 'Vereinigte Staaten', 'US', 42.36, -71.06, NULL, 'https://reasonstobecheerful.world/menstrual-blood-medical-possibilities/', 'Reasons to be Cheerful', 1000000, 70, 60, 57, 1, '2026-07-17T08:00:26+00:00', NULL, NULL, NULL, 'hope', 55, true, 'mensch', true, 'Ihre Ärztin sagte: Diesen Test gibt es nicht. Sie wusste, dass das nicht stimmt.', 'krass, warum bekommt man das sonst nirgends mit:', '{"hook": "Ein Test wurde ihr verweigert – dabei existierte er längst.", "aufloesung": "Statt aufzugeben, machte die Forscherin ihre eigene Gesundheit zum Projekt. Ihr Ansatz: Menstruationsblut, bisher als Abfall behandelt, über den Tampon für einfache Diagnosen nutzen.", "stille": "Aus Frust wurde Forschung. Aus Abfall ein Werkzeug."}'::jsonb, '„Diesen Test gibt es nicht“, sagte die Ärztin.
Sie wusste es besser – und machte daraus etwas, das vielen Frauen hilft. 👇

Quelle: Reasons to be Cheerful', false, 70, 'Ein Alltagsprodukt könnte Frauen einfache Gesundheitstests ermöglichen – ohne um sie kämpfen zu müssen.', 'Menstruationsblut galt als Abfall. Eine Forscherin macht daraus ein Diagnose-Werkzeug, das Frauen Tests bringt, die man ihnen sonst verweigert.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/menstrual-blood-medical-possibilities/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'In Großbritannien bekommen Menschen ohne Abschluss Bürojobs', 'Firmen stellen nach Fähigkeiten statt nach Diplom ein – und öffnen so ganze Karrieren.', 'Bruce Devlins Tech-Karriere floriert. In den vergangenen vier Jahren wurde er zweimal befördert, zuletzt zum Senior Quality Engineer bei einem Softwaretest-Unternehmen. Devlin, 26, hat sogar ein eigenes Werkzeug zur Überwachung von Systemausfällen gebaut und entwickelt nebenbei ein eigenes Videospiel. Bei den ScotlandIS Digital Technology Awards 2026 wurde er als „aufsteigender Stern“ ausgezeichnet.

Das Bemerkenswerte: Devlin hat keinen Hochschulabschluss. „Ich stelle mich oft als großen Nerd vor“, sagt der in Glasgow lebende Ingenieur. Schon als Kind habe er alles rund um Programmieren, Videospiele und Technik geliebt und einfach eigene Dinge bauen wollen.

Devlin steht für einen Wandel auf dem britischen Arbeitsmarkt: Immer mehr Firmen stellen nach nachgewiesenen Fähigkeiten ein, nicht nach dem Diplom. Für viele gut bezahlte Bürojobs war ein Studienabschluss lange Pflicht – oft auch dort, wo er für die tägliche Arbeit kaum eine Rolle spielt.

Diese Hürde trifft besonders Menschen, die sich Fähigkeiten selbst beigebracht haben oder aus finanziellen Gründen nicht studieren konnten. Fällt sie weg, öffnen sich Karrieren, die vorher verschlossen waren.

Der Nutzen wirkt in beide Richtungen: Talentierte Menschen bekommen eine Chance, die ihnen ein fehlendes Zertifikat sonst genommen hätte – und Unternehmen finden Fachkräfte, an denen sie zuvor blind vorbeigegangen wären.', 'Viele gut bezahlte Bürojobs setzen einen Hochschulabschluss voraus – auch dort, wo das Diplom für die eigentliche Arbeit kaum eine Rolle spielt. In Großbritannien stellen immer mehr Firmen nach nachgewiesenen Fähigkeiten statt nach Abschluss ein. So machen Menschen Karriere, denen der klassische Weg versperrt war – etwa ein Autodidakt, der es ohne Studium bis zum Senior-Ingenieur brachte. Das öffnet Aufstiegschancen für alle, die können, aber kein Diplom haben.', 'gemeinschaft', 'Vereinigtes Königreich', 'GB', 55.86, -4.25, NULL, 'https://reasonstobecheerful.world/skill-based-job-training-uk/', 'Reasons to be Cheerful', 500000, 75, 65, 56, 1, '2026-06-30T08:00:05+00:00', 10, 'Ein Abschluss ist ein Zeugnis von einer Schule oder Uni, das zeigt, was man gelernt hat.', 'Ist ein Zeugnis das Einzige, was zeigt, was ein Mensch kann?', 'pride', 50, true, 'mensch', true, 'Kein Uni-Abschluss. Zweimal befördert. Wie geht das plötzlich?', 'yeah. Fortschritt.', '{"hook": "Gut bezahlte Bürojobs verlangten fast immer ein Diplom.", "aufloesung": "In Großbritannien stellen immer mehr Firmen nach nachgewiesenem Können ein. Ein Autodidakt brachte es so ohne Studium bis zum Senior-Ingenieur – und wurde als aufsteigender Stern ausgezeichnet.", "stille": "Manchmal fehlt nicht das Können. Nur das Zertifikat."}'::jsonb, 'Kein Studium – und trotzdem Senior-Ingenieur.
Was sich am britischen Arbeitsmarkt gerade verschiebt, kannst du wischen. 👇

Quelle: Reasons to be Cheerful', false, 55, 'Firmen, die nach Können statt Diplom einstellen, öffnen Karrieren für alle, die es können.', 'Kein Studium, trotzdem zweimal befördert bis zum Senior-Ingenieur – weil britische Firmen anfangen, nach Können statt Diplom einzustellen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/skill-based-job-training-uk/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT '900 Millionen Dollar für sauberes Kochen in Afrika zugesagt', 'Fast eine Milliarde Menschen kocht über Feuer – die neue Zusage soll das ändern und Leben retten.', 'Fast eine Milliarde Menschen in Afrika kocht jeden Tag über Holzkohle oder Feuerholz. Um das zu ändern, braucht es nach Schätzungen 3,1 Milliarden Dollar – und die Summe der Zusagen wächst.

Afrikanische Länder haben 900 Millionen Dollar an neuen finanziellen Zusagen gesichert, um den Zugang zu sauberen Kochtechnologien auszubauen, wie die Internationale Energieagentur mitteilte. Die Mittel bauen auf den 2,2 Milliarden Dollar auf, die beim ersten Africa Clean Cooking Summit 2024 in Paris mobilisiert wurden – zusammen also über 3,1 Milliarden Dollar an Zusagen.

Warum das so wichtig ist: Holzkohle und Feuerholz befeuern nach wie vor die meisten afrikanischen Küchen, oft weil es keine andere Option gibt. Der dabei entstehende Rauch in geschlossenen Räumen ist hochgefährlich.

Die Innenraum-Luftverschmutzung durch offenes Kochen trägt jedes Jahr zu rund 850.000 Todesfällen bei. Betroffen sind vor allem Frauen und Kinder, die sich am längsten in der Nähe der Kochstelle aufhalten.

Saubere Kochlösungen – etwa effizientere Öfen oder Gas- und Stromkocher – bedeuten deshalb nicht nur weniger Rauch, sondern konkret weniger Krankheit und Tod. Zugleich schonen sie Wälder, weil weniger Holz verbrannt wird.

Geld allein löst das Problem nicht, und die Umsetzung bleibt die eigentliche Aufgabe. Doch dass die Zusagen weiter steigen, ist ein handfester Schritt für eine der stillsten Gesundheitskrisen der Welt.', 'Rund eine Milliarde Menschen in Afrika kocht täglich über Holzkohle oder offenem Feuer. Der Rauch in Innenräumen ist gefährlich: Er trägt jedes Jahr zu etwa 850.000 Todesfällen bei. Nun haben afrikanische Länder 900 Millionen Dollar an neuen Zusagen für saubere Kochtechnik gesichert – zusammen mit früheren Zusagen sind es über 3,1 Milliarden Dollar. Sauberere Öfen schützen vor allem die Gesundheit von Frauen und Kindern, die dem Rauch am stärksten ausgesetzt sind.', 'gesundheit', 'Afrika', '', 9.0, 8.7, NULL, 'https://www.optimistdaily.com/2026/07/africa-secures-900-million-in-new-clean-cooking-commitments/', 'The Optimist Daily', 1000000000, 80, 75, 68, 1, '2026-07-16T00:00:50+00:00', 10, 'Wenn man in einem Raum über offenem Feuer kocht, ist der Rauch schlecht für die Lunge.', 'Warum ist etwas so Alltägliches wie Kochen für manche Menschen gefährlich?', 'hope', 45, true, 'zahl', true, 'Kochen tötet in Afrika 850.000 Menschen im Jahr. Warum?', 'krass, dass sowas kaum jemand auf dem Schirm hat:', '{"hook": "Fast eine Milliarde Menschen kocht über offenem Feuer.", "aufloesung": "Der Rauch in geschlossenen Räumen trägt jährlich zu rund 850.000 Todesfällen bei, meist Frauen und Kinder. Jetzt sind über 3 Milliarden Dollar zugesagt, um saubere Kochtechnik zu bringen.", "stille": "Die tödlichste Gefahr steht manchmal in der eigenen Küche."}'::jsonb, '850.000 Tote im Jahr – durch etwas so Alltägliches wie Kochen.
Was sich gerade dagegen bewegt, siehst du beim Wischen. 👇

Quelle: The Optimist Daily', false, 90, 'Sauberere Öfen bedeuten weniger giftigen Küchenrauch – und retten vor allem Frauen und Kinder.', 'Küchenrauch tötet in Afrika jedes Jahr 850.000 Menschen. Jetzt sind über 3 Milliarden Dollar zugesagt, um saubere Öfen zu bringen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.optimistdaily.com/2026/07/africa-secures-900-million-in-new-clean-cooking-commitments/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Paris kühlt tausende Gebäude mit dem Wasser der Seine', 'Statt Klimaanlagen nutzt die Stadt kaltes Flusswasser – und will das System verdreifachen.', 'Jede Klimaanlage macht dasselbe: Sie zieht Wärme aus einem Gebäude und gibt sie nach draußen ab. An einem heißen Tag drücken Millionen Geräte gemeinsam die Straßentemperatur nach oben – und machen den nächsten heißen Tag noch schlimmer.

„Alles, was Energie braucht, gibt Wärme ab, und diese Wärme muss irgendwohin“, sagt Sophie Parison, eine Pariser Forscherin, die sich mit städtischer Hitze und Kühlung beschäftigt.

Paris baut seit dreißig Jahren an einem anderen Modell – und plant nun, es zu verdreifachen. Das System heißt „Fraîcheur de Paris“, was sich frei mit „die Frische von Paris“ übersetzen lässt. Es betreibt 120 Kilometer unterirdische Rohre unter der Stadt.

Durch diese Rohre fließt kaltes Wasser, das unter anderem aus der Seine gewonnen wird. Es kühlt Gebäude, ohne dass jedes Haus eine eigene Klimaanlage braucht, die ihre Abwärme auf die Straße bläst. Die Wärme landet nicht in der ohnehin aufgeheizten Stadtluft.

Angeschlossen sind bereits tausende Gebäude – von Museen über Krankenhäuser bis zu Büros. Mit der geplanten Verdreifachung sollen es deutlich mehr werden.

Der Reiz des Ansatzes liegt darin, dass er ein Kernproblem der Klimaanpassung löst: kühlen, ohne die Umgebung weiter aufzuheizen. Angesichts immer heißerer Sommer ist das ein Modell, von dem viele Städte lernen könnten.', 'Klimaanlagen kühlen zwar innen, heizen aber die Straßen draußen weiter auf – an heißen Tagen verschärft das die nächste Hitzewelle. Paris kühlt stattdessen seit dreißig Jahren tausende Gebäude mit kaltem Wasser aus der Seine, das durch ein unterirdisches Rohrnetz von 120 Kilometern fließt. Die Stadt will dieses System nun verdreifachen. So bleiben Räume kühl, ohne dass zusätzliche Abwärme die Umgebung aufheizt – ein Modell, das mit steigenden Temperaturen weltweit interessant wird.', 'klima', 'Frankreich', 'FR', 48.85, 2.35, NULL, 'https://www.optimistdaily.com/2026/07/how-paris-uses-the-seine-to-cool-thousands-of-buildings-without-ac/', 'The Optimist Daily', 1000000, 90, 75, 64, 1, '2026-07-15T00:00:34+00:00', 8, 'Eine Klimaanlage macht drinnen kühl, aber draußen wird es dadurch wärmer.', 'Wie könnte man eine Stadt kühlen, ohne dass es woanders heißer wird?', 'wonder', 60, false, NULL, true, NULL, 'krass, warum hört man das sonst nirgends:', NULL, NULL, false, 65, 'Paris kühlt Gebäude, ohne die Straßen weiter aufzuheizen – ein Vorbild für heißere Sommer überall.', 'Paris kühlt tausende Gebäude nicht mit Klimaanlagen, sondern mit kaltem Wasser aus der Seine – und will das jetzt verdreifachen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.optimistdaily.com/2026/07/how-paris-uses-the-seine-to-cool-thousands-of-buildings-without-ac/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Illinois schließt eine Lücke bei der Wechseljahres-Behandlung', 'Ein Gesetz lässt Fachkräfte gezielt für Menopause-Versorgung ausbilden – ohne neue Hürden.', 'Illinois'' Vizegouverneurin Juliana Stratton hatte eine Reihe von Gesprächen über finanzielle Absicherung mit Frauen im ganzen Bundesstaat organisiert. Sie erwartete, über Miete, Löhne und Lebensmittelpreise zu sprechen.

Stattdessen hörte sie immer wieder von etwas anderem: den Wechseljahren – und davon, was diese mit der Arbeit, dem Geld und dem Alltag der Frauen machten.

Das Gesetz, das daraus folgte, kam direkt aus diesen Gesprächen. Ende Mai verabschiedete der Gesetzgeber von Illinois einstimmig ein Gesetz, das es lizenzierten Gesundheitsfachkräften erlaubt, eine spezialisierte Fortbildung zur Versorgung rund um die Wechseljahre und die Zeit davor zu absolvieren.

Der Clou steckt im Detail: Die Fortbildung wird Teil einer ohnehin verpflichtenden Schulung – konkret der Sensibilisierung gegen unbewusste Vorurteile. Es braucht also keine neuen Pflichtstunden und kein zusätzliches Mandat. Das Wissen über die Menopause wird schlicht dort verfügbar gemacht, wo Fachkräfte sich sowieso weiterbilden.

Genau das macht die Maßnahme so klug: Sie schließt eine echte Versorgungslücke, ohne neue Bürokratie aufzubauen. Frauen, die bislang mit ihren Beschwerden oft allein gelassen wurden, treffen künftig auf besser geschultes Personal.

Dass die Idee aus dem direkten Zuhören entstand – und nicht am Schreibtisch – macht sie zu einem Beispiel dafür, wie man ein lange übersehenes Gesundheitsthema pragmatisch angeht.', 'Die Wechseljahre belasten viele Frauen im Berufsleben und im Alltag, doch ärztliches Fachwissen dazu ist oft lückenhaft. Der US-Bundesstaat Illinois hat einstimmig ein Gesetz beschlossen, das lizenzierten Gesundheitsfachkräften erlaubt, sich gezielt in der Behandlung der Wechseljahre weiterzubilden – eingebettet in bereits vorgeschriebene Schulungen, ohne neue Pflichtstunden. Die Idee entstand direkt aus Gesprächen mit betroffenen Frauen. So wird bessere Versorgung möglich, ohne zusätzliche Bürokratie.', 'gesundheit', 'Vereinigte Staaten', 'US', 39.8, -89.65, NULL, 'https://www.optimistdaily.com/2026/07/illinois-found-a-smarter-way-to-close-the-menopause-care-gap/', 'The Optimist Daily', 1000000, 85, 75, 60, 1, '2026-07-14T00:00:41+00:00', NULL, NULL, NULL, 'hope', 45, true, 'mensch', true, 'Sie wollten über Geld sprechen. Die Frauen redeten über etwas ganz anderes.', 'fand ich klug gemacht:', '{"hook": "Bei Gesprächen über Geld kam immer dasselbe Thema auf: die Wechseljahre.", "aufloesung": "Illinois beschloss einstimmig, Gesundheitsfachkräfte gezielt dafür fortzubilden – eingebettet in eine ohnehin verpflichtende Schulung, ohne neue Pflichtstunden.", "stille": "Zuhören zuerst. Das Gesetz kam danach."}'::jsonb, 'Sie luden Frauen ein, um über Geld zu reden.
Was sie stattdessen hörten, wurde zu einem Gesetz. 👇

Quelle: The Optimist Daily', false, 60, 'Bessere Versorgung in den Wechseljahren – ohne neue Hürden, weil die Fortbildung ins Bestehende passt.', 'Illinois wollte über Geld reden – und hörte von Frauen immer wieder über die Wechseljahre. Daraus wurde ein kluges Gesetz.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.optimistdaily.com/2026/07/illinois-found-a-smarter-way-to-close-the-menopause-care-gap/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Plastikflaschen an Fischernetzen retten fast 90 % der Delfine', 'Eine simple Idee senkt den Beifang drastisch – ohne dass die Fischer weniger fangen.', 'Delfine gehören zu den häufigsten Opfern der sogenannten Stellnetzfischerei: Sie verfangen sich in den fast unsichtbaren Netzen und ertrinken. Dieser ungewollte Beifang setzt vielen Delfin-Beständen weltweit zu.

Eine neue Studie zeigt einen verblüffend einfachen Ausweg. Fischer banden leere Plastikflaschen an ihre Kiemennetze – jene Netze, die im Wasser hängen und Fische an den Kiemen festhalten.

Die Flaschen wirken wie kleine Echo-Reflektoren: Delfine orten ihre Umgebung über Schallwellen, ähnlich einem Sonar. Die Flaschen werfen dieses Echo verstärkt zurück und machen das Netz für die Tiere „hörbar“, bevor sie hineingeraten.

Das Ergebnis war deutlich: Die Zahl der getöteten Delfine sank um fast 90 Prozent. Und – entscheidend für die Akzeptanz bei den Fischern – der Fischfang ging dabei nicht zurück.

Genau das macht die Idee so stark: Sie kostet fast nichts, verlangt keine neue Technik und schadet dem Einkommen der Fischer nicht. Eine leere Plastikflasche, sonst Abfall, wird hier zum Schutz für ein Meeressäugetier.

Ob sich der Ansatz überall übertragen lässt, müssen weitere Studien zeigen. Doch als Prinzip ist er ein Musterbeispiel dafür, dass die wirksamste Lösung nicht immer die teuerste ist.', 'Delfine verfangen sich oft in Stellnetzen der Fischerei und ertrinken – dieser sogenannte Beifang ist ein großes Problem für viele Bestände. In einer neuen Studie banden Fischer leere Plastikflaschen an ihre Netze; die Flaschen werfen im Wasser ein Echo zurück, das Delfine warnt. Das Ergebnis: fast 90 Prozent weniger tote Delfine – und der Fischfang blieb gleich hoch. Eine der billigsten denkbaren Lösungen verhindert so massenhaft Tierleid, ohne die Fischer etwas zu kosten.', 'tiere', 'International', '', NULL, NULL, NULL, 'https://www.anthropocenemagazine.org/2026/07/recycling-that-rescues-dolphins/?utm_source=rss&utm_medium=rss&utm_campaign=recycling-that-rescues-dolphins', 'Anthropocene Magazine', 100000, 70, 75, 62, 1, '2026-07-08T12:00:00+00:00', 8, 'Delfine ''sehen'' unter Wasser mit Geräuschen – wie ein Echo, das zurückkommt.', 'Warum ist die einfachste Lösung manchmal die beste?', 'wonder', 50, false, NULL, true, NULL, 'krass wie simpel die Lösung ist:', NULL, NULL, false, 40, 'Eine leere Flasche am Netz warnt Delfine per Echo – fast 90 % weniger sterben, ohne Ertragsverlust.', 'Fischer banden leere Plastikflaschen an ihre Netze – und plötzlich starben fast 90 % weniger Delfine. Der Fang blieb gleich.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.anthropocenemagazine.org/2026/07/recycling-that-rescues-dolphins/?utm_source=rss&utm_medium=rss&utm_campaign=recycling-that-rescues-dolphins');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Indien stellt seinen ersten selbstgebauten Wasserstoff-Zug vor', 'Ein Zug, der nur Wasserdampf ausstößt, soll die riesige Bahn sauberer machen.', 'Indien hat am Freitag seinen ersten im eigenen Land gebauten, mit Wasserstoff angetriebenen Zug vorgestellt – ein Schritt, der den Einsatz sauberer Energie in seinem riesigen Schienennetz ausweiten soll.

Der Zug besteht aus zwei wasserstoffbetriebenen Triebköpfen und acht Passagierwagen und wird im nordindischen Bundesstaat Haryana verkehren. Er kann bis zu 75 km/h schnell fahren und laut Bahnbehörden maximal rund 2.600 Fahrgäste befördern.

Das Besondere an einem Wasserstoff-Zug: Er erzeugt Strom aus Wasserstoff und Sauerstoff in einer sogenannten Brennstoffzelle. Als „Abgas“ entsteht dabei praktisch nur Wasserdampf – keine klimaschädlichen oder gesundheitsschädlichen Abgase wie beim Diesel.

Genau das ist der Nutzen: Auf Strecken, auf denen keine Oberleitung für elektrische Züge vorhanden ist, fahren bislang oft Dieselloks. Wasserstoffzüge können sie ersetzen und so den Ausstoß von Ruß und Treibhausgasen verringern.

Bemerkenswert ist auch, dass Indien den Zug selbst entwickelt und gebaut hat. Eigene Technik macht ein Land unabhängiger von Importen und erleichtert es, die Lösung im großen Maßstab und zu tragbaren Kosten auszurollen.

Ein einzelner Zug verändert noch kein Netz. Aber als erster Schritt in einem der größten Bahnsysteme der Welt kann er den Weg für viele weitere ebnen.', 'Indien hat ein riesiges Bahnnetz – und will es klimafreundlicher machen. Nun rollte der erste im Land selbst gebaute Zug mit Wasserstoff-Antrieb aus, der statt Abgasen nur Wasserdampf ausstößt. Er fährt im nordindischen Bundesstaat Haryana, erreicht bis zu 75 km/h und fasst rund 2.600 Fahrgäste. Wasserstoffzüge können dort Dieselzüge ersetzen, wo Oberleitungen fehlen – und so den Ausstoß schädlicher Abgase senken. Dass Indien den Zug selbst gebaut hat, macht die Technik unabhängiger und leichter verbreitbar.', 'klima', 'Indien', 'IN', 29.3, 76.3, NULL, 'https://news.mongabay.com/short-article/2026/07/india-launches-first-hydrogen-powered-train-built-in-the-country-to-expand-clean-energy-on-railways/', 'Mongabay', 1000000, 80, 70, 60, 1, '2026-07-17T17:34:04+00:00', 8, 'Ein Wasserstoff-Zug fährt sauber: Aus seinem Auspuff kommt nur Wasserdampf.', 'Was ist besser daran, wenn ein Land eine Technik selbst bauen kann?', 'hope', 45, false, NULL, true, NULL, 'les go – aus dem Auspuff kommt nur Wasserdampf:', NULL, NULL, false, 60, 'Ein Zug, der nur Wasserdampf ausstößt, kann Dieselzüge ersetzen – und Indien hat ihn selbst gebaut.', 'Indiens erster selbstgebauter Wasserstoff-Zug fährt – und stößt statt Abgasen nur Wasserdampf aus.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://news.mongabay.com/short-article/2026/07/india-launches-first-hydrogen-powered-train-built-in-the-country-to-expand-clean-energy-on-railways/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Pazifik-Inseln planen riesiges gemeinsames Meeresschutzgebiet', 'Vier Länder wollen einen der artenreichsten Ozeane der Welt über Grenzen hinweg schützen.', 'Eine Gruppe pazifischer Inselstaaten hat vereinbart, einen gewaltigen grenzüberschreitenden Meeresschutzkorridor offiziell einzurichten, der ihre Hoheitsgewässer umspannen soll.

Papua-Neuguinea, Vanuatu und Fidschi gaben beim ersten Melanesischen Ozean-Gipfel im Mai eine gemeinsame Erklärung ab, in der sie die Pläne für den Korridor ankündigten. Ende Juni schlossen sich die Salomonen der Initiative an.

Melanesien, eine Teilregion Ozeaniens im südwestlichen Pazifik, gehört zu den artenreichsten Gebieten der Welt. Die Region liegt im sogenannten Korallendreieck, dem globalen Zentrum der Korallenvielfalt. In ihren Gewässern kommen schätzungsweise 75 Prozent aller bekannten Korallenarten vor.

Warum ein zusammenhängender Korridor mehr bringt als viele kleine Schutzgebiete: Fische, Wale und Schildkröten wandern über weite Strecken. Ein durchgehend geschütztes Gebiet begleitet sie auf diesen Wegen, statt sie nur stückweise zu schützen. Das macht den Schutz deutlich wirksamer.

Ebenso bedeutsam ist die politische Botschaft. Vier Länder legen ihre Gewässer zusammen, um eine gemeinsame Lebensgrundlage zu bewahren. Der Ozean kennt keine Grenzen – und der Schutz muss auch keine kennen.

Noch ist es eine Absichtserklärung, und die Umsetzung wird die eigentliche Bewährungsprobe. Doch der Anspruch ist bemerkenswert: Naturschutz nicht als nationaler Flickenteppich, sondern als ein zusammenhängendes Ganzes.', 'Der westliche Pazifik gehört zu den artenreichsten Meeresgebieten der Erde – rund drei Viertel aller bekannten Korallenarten leben dort. Mehrere Inselstaaten – Papua-Neuguinea, Vanuatu, Fidschi und die Salomonen – haben vereinbart, ihre Gewässer zu einem gewaltigen grenzüberschreitenden Meeresschutzgebiet zu verbinden. Ein zusammenhängender Schutzkorridor lässt Fische und Meerestiere sicher wandern und schützt Korallenriffe wirksamer als einzelne kleine Gebiete. Es ist Naturschutz im ganz großen Maßstab – über Ländergrenzen hinweg.', 'klima', 'Papua-Neuguinea', 'PG', -6.3, 155.0, NULL, 'https://news.mongabay.com/2026/07/melanesian-nations-announce-intention-to-create-massive-ocean-reserve-corridor/', 'Mongabay', 1000000, 85, 70, 64, 1, '2026-07-17T17:16:21+00:00', 8, 'Ein Meeresschutzgebiet ist ein Teil des Meeres, in dem Tiere in Ruhe leben dürfen.', 'Warum ist es besser, ein großes Gebiet zu schützen als viele kleine Stücke?', 'hope', 40, false, NULL, true, NULL, 'krass, was die vier da zusammen anpacken:', NULL, NULL, false, 55, 'Vier Länder schützen gemeinsam einen der artenreichsten Ozeane – ein Korridor statt vieler Inseln.', 'Vier Pazifik-Länder legen ihre Meere zusammen, um einen der artenreichsten Ozeane der Welt gemeinsam zu schützen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://news.mongabay.com/2026/07/melanesian-nations-announce-intention-to-create-massive-ocean-reserve-corridor/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Uralte Steinbauten bringen Leben an die US-mexikanische Grenze zurück', 'Kleine Steinwälle bremsen das Wasser – und ausgetrocknetes Land ergrünt wieder.', 'In der Grenzregion zwischen den USA und Mexiko ist das Land vielerorts staubtrocken. Der Rancher Eduardo Ríos Colores zeigt auf ein knochentrockenes Bachbett, das sich durch die Landschaft zieht. „Es gab eine Zeit, da existierte dieser Bach nicht“, sagt er. „Früher standen hier viele Bäume, und die Bäume verhinderten, dass das Wasser die Erde wegspülte. Aber die Bäume sind vertrocknet.“

Das Problem ist typisch für Trockengebiete: Wasser kommt nicht gleichmäßig, sondern auf einmal, als Sturzflut. Statt zu versickern, rast es über den harten Boden, reißt Erde mit und ist schnell wieder weg. Das Land trocknet weiter aus.

Die Lösung ist verblüffend einfach und uralt: kleine Steinstrukturen, die quer in die Bachläufe gesetzt werden. Sie bremsen das strömende Wasser, sodass es versickern kann, und halten den Boden fest, statt ihn davontragen zu lassen.

Wo das Wasser länger bleibt, kehrt das Leben zurück: Gräser, Bäume und mit ihnen die Tiere. Aus vertrocknetem Land wird Schritt für Schritt wieder ein funktionierendes Ökosystem.

Das Besondere: Diese Technik kostet fast nichts, braucht keine Maschinen und knüpft an jahrhundertealtes Wissen an. Menschen schichten Steine – und geben der Natur damit die Bausteine zurück, die sie zum Heilen braucht.

Gegen die großen Trockenkrisen ist das kein Allheilmittel. Aber es zeigt, dass sich selbst ausgezehrtes Land erholen kann, wenn man dem Wasser hilft zu bleiben.', 'In trockenen Grenzregionen zwischen den USA und Mexiko rauscht der seltene Regen oft ungenutzt ab und reißt Erde mit sich – das Land trocknet immer weiter aus. Menschen bauen dort nun wieder uralte, einfache Steinstrukturen in die Bachläufe, die das Wasser bremsen, versickern lassen und den Boden halten. So kehren Pflanzen, Tiere und Feuchtigkeit in Gebiete zurück, die schon fast verloren waren. Eine jahrhundertealte Technik, fast ohne Kosten, hilft der Natur, sich selbst zu heilen.', 'klima', 'Mexiko', 'MX', 30.98, -110.3, NULL, 'https://news.mongabay.com/2026/07/ancient-rock-structures-help-restore-biodiversity-on-the-us-mexico-border/', 'Mongabay', 50000, 80, 65, 56, 1, '2026-07-17T10:49:04+00:00', 8, 'Wenn Regenwasser zu schnell wegfließt, kann der Boden nichts davon behalten.', 'Wie kann etwas so Einfaches wie ein Haufen Steine der Natur helfen?', 'wonder', 40, false, NULL, true, NULL, 'krass wie simpel und wie wirksam:', NULL, NULL, false, 35, 'Simple Steinwälle halten seltenen Regen im Boden – ausgetrocknetes Land wird wieder lebendig.', 'Ein paar Steine quer in den Bach gelegt – und ausgetrocknetes Grenzland ergrünt wieder. Eine uralte Technik, fast umsonst.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://news.mongabay.com/2026/07/ancient-rock-structures-help-restore-biodiversity-on-the-us-mexico-border/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Berlin geht mit einem Miet-Kataster gegen Wucher vor', 'Ein zentrales Verzeichnis soll überhöhte Mieten sichtbar machen – und Mieter schützen.', 'Wer in Berlin eine Wohnung sucht, ist nicht zu beneiden: Der Wohnraum ist knapp, die Konkurrenz groß und die Mieten sind hoch. 15,68 Euro kostet hier der Quadratmeter; in Städten wie Hagen, Halle oder Magdeburg zahlt man gerade einmal die Hälfte.

Einer der Gründe für die hohen Mieten: Vermieterinnen und Vermieter, die für ihre Wohnungen mehr Geld verlangen, als sie eigentlich dürften. Das Problem dabei ist nicht nur der Preis, sondern die fehlende Übersicht – wer überhöhte Mieten nachweisen will, hat es schwer.

Genau hier setzt der Beschluss an: Ein zentrales digitales Wohnungs- und Mietkataster soll künftig einen Überblick über alle Mietwohnungen in Berlin geben. Das hat das Berliner Abgeordnetenhaus in seiner letzten Sitzung vor der Sommerpause Anfang Juli beschlossen.

In dem Kataster sollen unter anderem Angaben zu Adresse, Wohnfläche und Zahl der Räume erfasst werden – die Grundlage, um erlaubte und tatsächlich verlangte Mieten zu vergleichen.

Der Nutzen ist konkret: Was sichtbar ist, lässt sich überprüfen. Ein solches Verzeichnis macht Mietwucher überhaupt erst nachweisbar und gibt Mieterinnen und Mietern ein Werkzeug an die Hand, um sich zu wehren.

Ob das Kataster in der Praxis hält, was es verspricht, wird die Umsetzung zeigen. Doch für eine Stadt mit Millionen Mietwohnungen ist mehr Transparenz auf dem Wohnungsmarkt ein Schritt, der viele Menschen im Alltag betrifft.', 'In Berlin sind Wohnungen knapp und die Mieten hoch – ein Grund sind Vermieter, die mehr verlangen, als eigentlich erlaubt ist. Das Berliner Abgeordnetenhaus hat nun beschlossen, ein zentrales digitales Wohnungs- und Mietkataster aufzubauen, das alle Mietwohnungen der Stadt mit Daten wie Adresse, Wohnfläche und Miete erfasst. Damit werden überhöhte Mieten überhaupt erst nachweisbar. Für Millionen Mieterinnen und Mieter kann das ein handfestes Werkzeug gegen Mietwucher werden.', 'gemeinschaft', 'Deutschland', 'DE', 52.52, 13.4, NULL, 'https://perspective-daily.de/article/5068-zu-hohe-miete-berlin-macht-ernst-gegen-wucher/probiere?pk_campaign=rss_feed', 'Perspective Daily', 2000000, 80, 75, 62, 1, '2026-07-19T00:00:00+02:00', 12, 'Miete ist das Geld, das man jeden Monat dafür zahlt, in einer Wohnung zu wohnen.', 'Warum hilft es, wenn Preise für alle sichtbar sind?', 'relief', 90, false, NULL, true, NULL, 'endlich mal ein konkretes Werkzeug gegen Mietwucher:', NULL, NULL, false, 60, 'Ein Miet-Kataster macht überhöhte Mieten nachweisbar – ein Werkzeug für Millionen Mieter.', 'Berlin baut ein Kataster aller Mietwohnungen auf – damit überhöhte Mieten endlich nachweisbar werden.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://perspective-daily.de/article/5068-zu-hohe-miete-berlin-macht-ernst-gegen-wucher/probiere?pk_campaign=rss_feed');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Kindergeld soll künftig automatisch aufs Konto kommen', 'Ohne Antrag, ohne Papierkram – die Umstellung spart 205.000 Stunden Bürokratie.', 'Kindergeld soll künftig automatisch auf dem Konto landen – ohne Antrag, ohne Papierkram. Das soll Familien entlasten, heißt es im Gesetzentwurf, den der Bundestag am 9. Juli verabschiedet hat. Der Bundesrat muss noch zustimmen.

Bisher müssen Eltern das Kindergeld beantragen. Was nach einer Formalität klingt, ist in der Praxis eine echte Hürde: Anträge gehen unter, werden falsch ausgefüllt oder aus Unwissen gar nicht erst gestellt – gerade dort, wo die Unterstützung besonders gebraucht wird.

Die Neuerung erfolgt schrittweise. Ab Frühjahr 2027 gilt sie zunächst für Neugeborene in Familien, die bereits für ältere Geschwister Kindergeld beziehen – der Grund: Die Daten der Familienkasse liegen hier schon vor. Ende 2027 soll die Leistung dann auch für das erste Kind automatisch fließen.

Die erwartete Entlastung ist beträchtlich: Rund 205.000 Stunden Bürokratie sollen dadurch wegfallen – Zeit, die weder Familien noch Behörden mehr mit Anträgen verbringen müssen.

Der eigentliche Fortschritt steckt im Prinzip: Eine Leistung, die ohnehin allen Familien zusteht, wird nicht mehr an einen Antrag geknüpft. Hilfe erreicht die Menschen, statt an Formularen zu scheitern.

Ein konkreter Endtermin für die vollständige Umsetzung wird noch nicht genannt – zuerst müssen die technischen Voraussetzungen geschaffen werden. Doch die Richtung ist klar: weniger Papierkram, mehr Selbstverständlichkeit.', 'Bisher müssen Familien Kindergeld beantragen – ein Aufwand, der leicht untergeht oder scheitert. Der Bundestag hat beschlossen, dass Kindergeld künftig automatisch aufs Konto fließen soll, ohne Antrag und ohne Papierkram. Das entlastet Familien und spart geschätzte 205.000 Stunden Bürokratie. Die Umstellung kommt schrittweise ab 2027. Es ist ein Beispiel dafür, wie der Staat Leistungen einfacher zugänglich macht – damit Hilfe die Menschen erreicht, statt an Formularen zu scheitern.', 'gemeinschaft', 'Deutschland', 'DE', 52.52, 13.4, NULL, 'https://perspective-daily.de/article/5066-diese-aenderung-spart-205000-stunden-buerokratie/probiere?pk_campaign=rss_feed', 'Perspective Daily', 10000000, 90, 80, 66, 1, '2026-07-19T00:00:00+02:00', 10, 'Kindergeld ist Geld, das der Staat Familien für ihre Kinder gibt.', 'Warum ist es gut, wenn man Hilfe bekommt, ohne extra danach fragen zu müssen?', 'relief', 95, false, NULL, true, NULL, 'endlich weniger Papierkram für Familien:', NULL, NULL, false, 80, 'Kindergeld ohne Antrag heißt: Hilfe erreicht Familien, statt an Formularen zu scheitern.', 'Kindergeld soll bald automatisch aufs Konto kommen – ohne Antrag. Das spart 205.000 Stunden Papierkram.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://perspective-daily.de/article/5066-diese-aenderung-spart-205000-stunden-buerokratie/probiere?pk_campaign=rss_feed');

