INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Selbst angebaute Pflanze schützt vor Mücken wie teures Mittel', 'Eine Lotion aus Katzenminze wirkte im Test so gut wie das Standardmittel DEET — und lässt sich in Uganda vor Ort anbauen.', 'Der beste Schutz vor Malaria ist der Stich, der nie passiert. Genau daran scheitert er in vielen ländlichen Regionen Ugandas allerdings an einer banalen Hürde: am Preis.

„DEET liegt außerhalb der Preisklasse der meisten ugandischen Subsistenzbauern, kommerziell erhältliche Mückenschutzmittel zu kaufen ist für sie schlicht nicht praktikabel“, sagt Simon Scofield, Dozent an der Universität Cardiff in Wales. DEET ist der Wirkstoff, der in den meisten handelsüblichen Mückensprays steckt.

Scofields Team hat gemeinsam mit ugandischen Forschenden nach einer Alternative gesucht, die vor Ort wachsen kann — und ist bei der Katzenminze gelandet, botanisch *Nepeta cataria*. Ihr ätherisches Öl enthält **Nepetalacton**, jene Substanz, die Katzen in Euphorie versetzt. Auf Mücken wirkt sie offenbar völlig anders: Sie stört deren Geruchssinn.

In Labortests, vorgestellt auf einer internationalen Wissenschaftskonferenz im italienischen Florenz, hielt eine Hautlotion mit **6 Prozent Nepetalacton** Mücken ebenso zuverlässig davon ab, auf einem menschlichen Arm zu landen, wie DEET. Eine Zubereitung mit 2 Prozent schnitt nur geringfügig schlechter ab.

Der entscheidende Vorteil liegt nicht in der Wirksamkeit, sondern in der Herstellbarkeit. Katzenminze ist leicht anzubauen, das ätherische Öl lässt sich einfach destillieren. Und es riecht besser als DEET. Traditionell wird die Pflanze ohnehin seit Jahrhunderten als Mückenschutz verwendet.

„Wir wollten ein Mittel entwickeln, das hochwirksam ist, aber auch die Menschen vor Ort in den Produktionszyklus einbindet, sodass es möglichst wenig kostet“, sagt Scofield.

Aus der Forschung ist inzwischen ein Produkt geworden: eine Lotion namens DSK, die Scofield gemeinsam mit Menschen vor Ort entwickelt hat, um sie verkaufen zu können — und die Herstellung damit von Fördergeldern unabhängig zu machen.

Patentieren lässt sich das Ganze nicht. Die Lotion besteht nur aus ätherischem Öl, Stabilisatoren und gängigen kosmetischen Grundstoffen. Was nach einem wirtschaftlichen Nachteil klingt, ist in diesem Fall die eigentliche Pointe: Niemand kann den Preis kontrollieren.

„Sobald wir wissen, dass wir das Mittel günstig verkaufen und verteilen können, sollte das ein sich selbst tragendes System erzeugen, bei dem das Geld an jeder Stufe der Entwicklung an alle zurückfließt“, sagt Scofield.

Der Hintergrund ist ernst. „Es besteht ein echter Bedarf, die Abhängigkeit von Malaria-Medikamenten zu verringern, weil Malaria Resistenzen gegen Medikamente entwickeln kann“, so Scofield. Mückenschutzmittel gehören zu den wichtigsten Maßnahmen, um das Risiko zu senken — indem sie Landungen und Stiche von vornherein verhindern.

Noch stammen die Daten aus dem Labor, nicht aus dem Alltag ganzer Dörfer. Aber der Weg von der Pflanze im Garten zur Lotion auf der Haut ist ungewöhnlich kurz.', 'Malaria wird von Mücken übertragen, und der wirksamste Schutz ist, gar nicht erst gestochen zu werden — doch handelsübliche Mückenmittel mit dem Wirkstoff DEET sind für viele Kleinbauern in Uganda schlicht zu teuer. Ein Team walisischer und ugandischer Forscher hat nun eine Lotion aus Katzenminze getestet: Eine Zubereitung mit 6 Prozent des Pflanzenstoffs Nepetalacton hielt Mücken im Labor genauso zuverlässig vom Landen auf der Haut ab wie DEET. Das ist strukturell wichtig, weil die Pflanze leicht anzubauen ist und das Öl einfach destilliert werden kann — die Herstellung bleibt also vor Ort, statt Geld für Importe abfließen zu lassen. Weil der Malaria-Erreger zunehmend Resistenzen gegen Medikamente entwickelt, gewinnt jeder Schutz, der Stiche von vornherein verhindert, an Bedeutung.', 'gesundheit', 'Uganda', 'UG', 1.3733, 32.2903, NULL, 'https://www.goodnewsnetwork.org/homegrown-catnip-lotion-proves-to-be-an-effective-mosquito-repellent-in-rural-uganda/', 'Good News Network', 500000, 70, 70, 66, 2, '2026-07-17T18:30:00+00:00', 8, 'Malaria ist eine schwere Krankheit, die man bekommen kann, wenn eine bestimmte Mücke einen sticht.', 'Warum ist es manchmal besser, wenn etwas nicht patentiert werden kann?', 'pride', 55, true, 'wow', false, 'Das Kraut, das Katzen high macht, hält Mücken ab.', NULL, '{"hook": "Das Kraut, das Katzen high macht, hält Mücken ab.", "aufloesung": "Eine Lotion aus Katzenminze wirkte im Labor so gut wie DEET, das Standardmittel — für viele Kleinbauern in Uganda unbezahlbar. Die Pflanze wächst vor Ort, das Öl ist leicht zu destillieren. Patentieren lässt sie sich nicht: Das hält den Preis unten.", "stille": "Manchmal wächst die Lösung schon da, wo das Problem ist."}'::jsonb, 'Der beste Schutz vor Malaria ist der Stich, der nie passiert.
Nur kostet das Mittel dafür mehr, als viele Familien haben. Bis jemand im Garten nachgesehen hat. 👇

Quelle: Good News Network', false, 55, 'Eine Pflanze aus dem eigenen Garten schützt vor Malaria-Mücken so gut wie das teure Importmittel.', 'Katzenminze — das Kraut, das Katzen verrückt macht — hält Mücken im Test genauso gut ab wie das teure Standardmittel. Und wächst einfach im Garten.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.goodnewsnetwork.org/homegrown-catnip-lotion-proves-to-be-an-effective-mosquito-repellent-in-rural-uganda/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Passende Mahlzeiten auf Rezept machen Kranke messbar gesünder', 'In Massachusetts bekommen chronisch Kranke ärztlich abgestimmte Mahlzeiten geliefert — eine Studie zeigt jetzt deutliche Verbesserungen.', 'Es ist einer der ältesten Sätze der Medizin und einer der am seltensten umgesetzten: dass Essen ein Teil der Behandlung ist. In den USA wird er gerade überprüft — mit Zahlen.

Rund ein Dutzend US-Bundesstaaten bietet Menschen, die über das staatliche Gesundheitsprogramm Medicaid versichert sind, sogenannte **medizinisch abgestimmte Mahlzeiten** an. Gemeint sind fertig zubereitete Gerichte, die nach Hause geliefert und von einer Ernährungsfachkraft individuell auf eine Erkrankung zugeschnitten werden — etwa auf Diabetes, Herzschwäche oder chronisches Nierenversagen.

Eine neue Studie kommt zu dem Ergebnis, dass solche Programme die Gesundheit der Teilnehmenden **deutlich verbessern**.

Massachusetts war der erste Bundesstaat, der solche Mahlzeiten breit für Medicaid-Versicherte mit ernährungsbedingten Erkrankungen anbot. Genau deshalb konzentrierten Forschende der Tufts University, der University of Massachusetts Chan Medical School und weiterer Einrichtungen ihre Untersuchung auf diesen Staat. Sie fanden, dass Medicaid-Versicherte in Massachusetts, die solche Mahlzeiten erhielten, gesundheitlich messbar besser dastanden.

Die Idee gehört zu einer größeren Bewegung, die im Englischen unter dem Schlagwort *food is medicine* läuft — Ernährung als Mittel, um chronische Krankheiten zu verhindern und zu behandeln, statt sie nur medikamentös zu verwalten.

Diese Bewegung hat in den vergangenen Jahren an Fahrt gewonnen, auch politisch. Robert F. Kennedy Jr., Gesundheitsminister der Vereinigten Staaten, hat das Konzept wiederholt unterstützt und auf das Potenzial verwiesen, die Gesundheit zu verbessern und zugleich Kosten im Gesundheitswesen zu senken.

Dass die politische Rückendeckung allein noch keine Qualität garantiert, zeigte allerdings ein Vorfall im vergangenen Jahr: Kennedy geriet in die Kritik, nachdem er ein Unternehmen gelobt hatte, das solche Mahlzeiten für Medicaid- und Medicare-Versicherte herstellt. Die Nachrichtenagentur Associated Press sah sich das Angebot an und fand auf der Speisekarte genau jene hochverarbeiteten, salz- und zuckerreichen Produkte, die Kennedy sonst kritisiert.

Das ist die eigentliche Schwachstelle des Ansatzes — und zugleich der Grund, warum die Studie zählt. Sie misst nicht die Idee, sondern ein konkretes, über Jahre laufendes Programm eines Bundesstaats.

Für Gesundheitssysteme ist das eine ungewöhnlich pragmatische Aussicht. Anders als bei einem neuen Wirkstoff braucht es hier keine Zulassung und keine Jahre der Entwicklung. Es braucht eine Küche, eine Ernährungsfachkraft und eine Lieferadresse.', 'Bei Krankheiten wie Diabetes, Herzschwäche oder chronischem Nierenleiden entscheidet das tägliche Essen mit darüber, wie schnell sich der Zustand verschlechtert — nur fehlt vielen Erkrankten das Geld oder das Wissen für die passende Ernährung. In den USA liefern rund ein Dutzend Bundesstaaten deshalb sogenannte medizinisch abgestimmte Mahlzeiten: fertige Gerichte, die eine Ernährungsfachkraft auf die jeweilige Krankheit zuschneidet und nach Hause bringen lässt. Eine neue Untersuchung von Forschenden der Tufts University und der Universität von Massachusetts zeigt, dass sich der Gesundheitszustand der Teilnehmenden deutlich verbessert hat. Das ist wichtig, weil hier nicht ein neues Medikament wirkt, sondern etwas, das jedes Gesundheitssystem sofort bereitstellen könnte.', 'gesundheit', 'Vereinigte Staaten', 'US', 42.4072, -71.3824, NULL, 'https://reasonstobecheerful.world/food-is-medicine-study/', 'Reasons to be Cheerful', 200000, 75, 85, 68, 2, '2026-07-16T08:00:05+00:00', 10, 'Manche Krankheiten werden besser oder schlechter, je nachdem was man isst.', 'Wenn Essen wie Medizin wirken kann — wer sollte es dann bezahlen?', 'hope', 65, true, 'sieg', false, 'Essen auf Rezept — und es wirkt messbar.', NULL, '{"hook": "Essen auf Rezept — und es wirkt messbar.", "aufloesung": "In Massachusetts liefert das Gesundheitsprogramm chronisch Kranken Mahlzeiten, die eine Ernährungsfachkraft auf ihre Krankheit zuschneidet. Eine neue Studie zeigt deutliche Verbesserungen. Kein neues Medikament nötig — nur eine Küche und eine Lieferadresse.", "stille": "Manchmal ist die Behandlung das, was auf dem Teller liegt."}'::jsonb, 'Bei Diabetes oder Herzschwäche entscheidet das Abendessen mit — nur fehlt vielen das Geld dafür.
Ein US-Bundesstaat hat es einfach übernommen. Mit messbarem Ergebnis. 👇

Quelle: Reasons to be Cheerful', false, 55, 'Passendes Essen auf Rezept verbessert die Gesundheit chronisch Kranker — ohne neues Medikament.', 'In Massachusetts bekommen chronisch Kranke Mahlzeiten geliefert, die auf ihre Krankheit abgestimmt sind. Eine Studie zeigt jetzt: Es wirkt.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/food-is-medicine-study/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Grenoble ersetzt Werbetafeln durch Bäume', 'Die französische Stadt entfernt Reklame aus dem Straßenbild und pflanzt stattdessen Baumreihen und Radwege.', '„Hier war früher ein massiver Betonblock, da stand eine Litfaßsäule, das war nicht so schön“, sagt Gilles Namur und lässt die Hand über den Cours Lafontaine gleiten, eine Straße, die durch das historische Zentrum von Grenoble führt.

Heute bietet sich ein völlig anderes Bild. Die Straße wurde umgestaltet und hat einen großzügigen Radweg bekommen. Eine lange Baumreihe wurde entlang der einen Seite gepflanzt, passend zur Reihe auf dem gegenüberliegenden Gehweg. Und die Werbung ist verschwunden.

Mit dem Blick auf die Berge in der Ferne, die schon Stendhal, der berühmteste Schriftsteller der Stadt, beschrieben hat, ergibt das eine ausgesprochen angenehme Aussicht. Dass sie weit vom Times Square entfernt ist, wäre eine Untertreibung.

„Unser Leben ist heute voller Werbung, voller konsumorientierter Bilder, die negative Auswirkungen auf die Gesellschaft haben, auf die Art, wie wir leben“, sagt Namur, in Grenoble stellvertretender Bürgermeister für Lebensqualität, Biodiversität und Mobilität. „Wir wollen versuchen, das so weit wie möglich zu reduzieren.“

Hier, am Fuß der französischen Alpen, wird ein Feldzug gegen die **visuelle Verschmutzung** geführt.

Der Begriff ist weniger etabliert als andere Formen der Verschmutzung, meint aber etwas durchaus Messbares: In Grenobles Fall vor allem Werbeinhalte, daneben auch schlicht hässliche bauliche Strukturen. Die sozialen Folgen sind erforscht — visuelle Verschmutzung kann Konsum und Überkonsum befeuern, der psychischen Gesundheit schaden und sexistische Bildsprache verbreiten.

In einer Zeit der Informationsüberflutung gehört die Stadt zu den Vorreitern beim Versuch, die Reichweite dieser Bilder im öffentlichen Raum zu begrenzen.

Bemerkenswert ist daran vor allem, was es die Stadt kostet. Werbeflächen im Stadtraum sind für Kommunen üblicherweise eine verlässliche Einnahmequelle — sie werden verpachtet, das Geld fließt in den Haushalt. Wer sie abbaut, verzichtet auf diese Einnahmen und muss die Umgestaltung zusätzlich bezahlen.

Genau deshalb ist Grenoble interessant für andere Städte. Es geht nicht um eine Geste, sondern um die Frage, ob eine Kommune bereit ist, öffentlichen Raum als etwas zu behandeln, das nicht vermietet werden muss.

Was dabei entsteht, ist unspektakulär und genau deshalb überzeugend: eine Straße mit Bäumen, einem Radweg und freier Sicht auf die Berge — dort, wo vorher Beton und Reklame standen.', 'Werbung im öffentlichen Raum gilt als „visuelle Verschmutzung“ — sie ist kaum zu vermeiden, befeuert Konsumdruck, belastet die psychische Gesundheit und transportiert oft sexistische Bilder. Die französische Stadt Grenoble am Fuß der Alpen entfernt deshalb Reklameflächen aus dem Straßenbild und gestaltet Straßen neu: Am Cours Lafontaine im historischen Zentrum stehen heute ein breiter Radweg und zwei Baumreihen dort, wo zuvor ein Betonblock und eine Litfaßsäule standen. Das ist bemerkenswert, weil Städte ihre Werbeflächen üblicherweise verpachten und damit auf Einnahmen verzichten müssen. Grenoble gilt inzwischen als Vorreiter für andere Kommunen, die den öffentlichen Raum zurückgewinnen wollen.', 'gemeinschaft', 'Frankreich', 'FR', 45.1885, 5.7245, NULL, 'https://reasonstobecheerful.world/grenoble-beauty-over-billboards/', 'Reasons to be Cheerful', 160000, 80, 70, 56, 2, '2026-07-13T08:00:40+00:00', 8, 'Werbetafeln sind große Plakate an der Straße, für die Firmen der Stadt Geld zahlen, damit sie dort hängen dürfen.', 'Was würdest du an eure Straße stellen, wenn du entscheiden dürftest?', 'hope', 75, false, NULL, false, NULL, NULL, NULL, NULL, false, 40, 'Eine Stadt verzichtet auf Werbeeinnahmen und stellt stattdessen Bäume hin — der Blick gehört wieder allen.', 'Grenoble baut seine Werbetafeln ab und pflanzt Bäume an die Stelle. Auf die Pachteinnahmen verzichtet die Stadt einfach.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/grenoble-beauty-over-billboards/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Briten ohne Studium kommen wieder an gute Bürojobs', 'Firmen streichen den Hochschulabschluss aus Stellenanzeigen — und stellen stattdessen nach Fähigkeiten ein.', 'Bruce Devlin ist 26, arbeitet als leitender Qualitätsingenieur bei der Softwaretest-Firma 2i in Glasgow und wurde in den vergangenen vier Jahren zweimal befördert. Er hat ein eigenes Überwachungswerkzeug für Systemausfälle gebaut und entwickelt nebenbei ein Videospiel. Bei den schottischen Digitaltechnik-Preisen 2026 wurde er als „aufstrebendes Talent“ ausgezeichnet.

„Ich stelle mich oft als großer Nerd vor“, sagt Devlin. „Ich war schon immer total darauf aus, an Programmen und Computern herumzubasteln.“

Einen Hochschulabschluss hat er nicht. Und lange sah es so aus, als würde ihn genau das dauerhaft von solchen Stellen fernhalten.

Von seinem **zehnten bis zu seinem 21. Lebensjahr** pflegte Devlin seine alleinerziehende Mutter, die an einer Borderline-Persönlichkeitsstörung litt. Er übernahm Einkauf, Kochen und Putzen, sorgte dafür, dass sie ihre Arzttermine wahrnahm, ihre Medikamente einnahm und die Rechnungen aus dem Pflege- und Behindertengeld bezahlt wurden.

Zur Schule ging er weiter, aber ohne Zeit zum Lernen kam er gerade so durch. Ein Studium stand nie zur Debatte. Selbst ein Nebenjob war nicht drin.

„Es war ein Vollzeitjob — du bist immer da und auf Abruf“, sagt Devlin. „Ich hatte kaum ein Sozialleben und in der Schule lief nicht viel. Schule war manchmal zu viel, und meine Mutter zu pflegen war die Grenze dessen, was ich leisten konnte.“ Und: „Ich komme aus einer Familie ohne Arbeit, ich hatte also keinen besonders guten Start.“

Geschichten wie seine enden in der Regel nicht in einem Ingenieursbüro. Der Grund ist ein Mechanismus, der selten offen benannt wird: Der Hochschulabschluss dient vielen Arbeitgebern als bequemer Vorfilter — nicht, weil die Tätigkeit ihn erfordert, sondern weil er die Zahl der Bewerbungen reduziert. Wer keinen hat, wird aussortiert, bevor irgendjemand seine Fähigkeiten überhaupt ansieht.

In Großbritannien setzt sich inzwischen ein anderer Ansatz durch, für den sich der Begriff *skills-based hiring* eingebürgert hat — Einstellung nach nachgewiesenem Können statt nach Zeugnissen. Unternehmen streichen die Abschluss-Anforderung aus Stellenanzeigen und prüfen stattdessen in Aufgaben und Tests, was Bewerberinnen und Bewerber tatsächlich beherrschen.

Für Menschen wie Devlin verändert das die Ausgangslage grundlegend. Sein Können war die ganze Zeit da — es hatte nur niemand danach gefragt.

Der Effekt reicht über einzelne Lebensläufe hinaus. Pflegende Angehörige, Kinder aus einkommensschwachen Familien, Menschen mit unterbrochenen Bildungswegen — sie alle scheitern überproportional an einem Filter, der mit der eigentlichen Arbeit wenig zu tun hat. Fällt er weg, öffnet sich ein Arbeitsmarkt, der ihnen vorher praktisch verschlossen war.

Devlin investiert sein Gehalt inzwischen weitgehend in eigene Projekte. „Ich habe jetzt einen Haufen Nebenprojekte, in die ich im Grunde mein ganzes Gehalt zurückstecke, um coole Technik-Werkzeuge und Videospiele zu machen.“', 'In vielen Branchen ist der Hochschulabschluss zur unausgesprochenen Eintrittskarte geworden, auch für Tätigkeiten, die man ohne Studium erlernen kann — wer als junger Mensch keine Zeit oder kein Geld dafür hatte, blieb draußen. In Großbritannien gehen inzwischen Unternehmen dazu über, den Abschluss aus ihren Anforderungen zu streichen und stattdessen zu prüfen, was jemand tatsächlich kann. Der Softwaretester Bruce Devlin aus Glasgow, der von seinem zehnten bis 21. Lebensjahr seine kranke Mutter pflegte und deshalb nicht studieren konnte, wurde auf diesem Weg zweimal befördert und als aufstrebendes Talent bei einem schottischen Technologiepreis ausgezeichnet. Das ist strukturell bedeutsam, weil es einen der wirksamsten sozialen Filter im Arbeitsmarkt lockert.', 'gemeinschaft', 'Vereinigtes Königreich', 'GB', 55.8642, -4.2518, NULL, 'https://reasonstobecheerful.world/skill-based-job-training-uk/', 'Reasons to be Cheerful', 300000, 70, 70, 62, 2, '2026-06-30T08:00:05+00:00', 12, 'Ein Hochschulabschluss ist ein Zeugnis von der Universität — manche Jobs verlangen es, obwohl man die Arbeit auch ohne lernen kann.', 'Woran würdest du erkennen, ob jemand etwas wirklich gut kann?', 'hope', 70, true, 'mensch', false, 'Ab 10 pflegte er seine Mutter. Studium: unmöglich.', NULL, '{"hook": "Ab 10 pflegte er seine Mutter. Studium: unmöglich.", "aufloesung": "Bruce Devlin aus Glasgow versorgte elf Jahre lang seine kranke Mutter. Für die Schule blieb kaum Zeit, für ein Studium gar keine. Heute ist er leitender Qualitätsingenieur und wurde als aufstrebendes Talent ausgezeichnet — weil Firmen anfangen, nach Können statt nach Abschluss zu fragen.", "stille": "Sein Können war immer da. Es hat nur keiner danach gefragt."}'::jsonb, 'Elf Jahre lang war er der Erwachsene zu Hause. Einkaufen, kochen, Medikamente, Rechnungen — mit zehn Jahren.
Was aus ihm geworden ist. 👇

Quelle: Reasons to be Cheerful', false, 55, 'Wer wegen Pflege oder Geldmangel nicht studieren konnte, kommt wieder an Jobs, die er längst könnte.', 'Er pflegte ab 10 seine kranke Mutter, Studium war nie drin. Heute ist er leitender Ingenieur — weil Firmen aufhören, nach dem Abschluss zu fragen.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/skill-based-job-training-uk/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Ein Farb-Code schützt Restaurant-Personal vor Belästigung', 'Gelb, Orange, Rot: Ein Team in Kalifornien machte Belästigung meldbar — ohne dass Beschäftigte sich rechtfertigen müssen.', 'Der Vorfall, der alles auslöste, ereignete sich 2015 in einem Restaurant, das für Makkaroni mit Käse bekannt ist. Ein vierfacher Familienvater griff einer Kellnerin unter die Bluse — vor den Augen seiner Kinder.

„Wir sind ein Familienrestaurant, unsere Spezialität ist Mac and Cheese!“, erinnert sich Erin Wade, Köchin und Inhaberin des Homeroom im kalifornischen Oakland, mit anhaltender Fassungslosigkeit.

Sie war erschüttert, als sie erfuhr, dass die meisten ihrer Beschäftigten in ihrem Restaurant sexuelle Belästigung erlebt hatten. Je mehr sie mit ihnen sprach, desto klarer wurde allerdings: Ihr Betrieb war kein besonderer Brennpunkt. „Meine Leute sagten, sie hätten Belästigung in jedem Restaurant erlebt, in dem sie gearbeitet haben, aber sie hätten es nie gewagt, das Thema bei ihrer Leitung anzusprechen.“

Die Zahlen stützen das. Laut einer Untersuchung der Organisation Restaurant Opportunities Centers United aus dem Jahr 2014 berichten **fast 80 Prozent** der weiblichen und **49 Prozent** der männlichen Beschäftigten, am Arbeitsplatz sexuell belästigt worden zu sein — durch Gäste, Küchenchefs und Kolleginnen und Kollegen. Da einer Umfrage zufolge zwei Drittel aller Erwachsenen in den USA irgendwann in ihrem Leben in der Gastronomie gearbeitet haben, ist das Ausmaß enorm.

Bestehende Schulungsprogramme, etwa Trainings für couragiertes Eingreifen, zeigen kurzfristig Wirkung, aber ohne umfassendere Veränderungen in der Organisation kaum dauerhafte.

Wade entwickelte deshalb gemeinsam mit weiblichen Beschäftigten ein System, das simpel genug war, um bei knapp 100 Mitarbeitenden auch mitten im chaotischen Abendgeschäft zu funktionieren. Das Verhalten von Gästen wird nach **Farben** eingeteilt: gelb, orange oder rot.

„Gelb bezeichnet eine gruselige Stimmung oder einen unappetitlichen Blick“, erklärt Wade. „Orange bedeutet Bemerkungen mit sexuellem Unterton, etwa bestimmte Komplimente über das Aussehen einer Beschäftigten. Rot signalisiert explizite sexuelle Bemerkungen, Berührungen oder wiederholte Vorfälle in der Orange-Kategorie, nachdem den Betreffenden gesagt wurde, dass die Kommentare unerwünscht sind.“

Erlebt jemand eine Belästigung, meldet er die Farbe — und die Leitung reagiert entsprechend gestaffelt.

Der eigentliche Kunstgriff liegt darin, was das System den Betroffenen **erspart**. Wer im vollen Restaurant erklären muss, was genau gesagt wurde, in welchem Ton, und ob das nun schlimm genug war, meldet in der Regel gar nichts. Wer „Tisch neun ist orange“ sagen kann, meldet es.

Damit verschiebt sich die Beweislast weg von der Person, der etwas passiert ist. Sie muss nichts mehr begründen, sondern nur benennen — und die Reaktion ist vorher festgelegt, nicht Verhandlungssache mit dem Chef.

Es ist eine Lösung ohne Budget, ohne Software und ohne Rechtsabteilung. Sie besteht aus drei Wörtern und der Zusage, dass darauf etwas folgt.', 'Sexuelle Belästigung durch Gäste gehört in der Gastronomie zum Alltag: Fast 80 Prozent der weiblichen und 49 Prozent der männlichen Beschäftigten haben sie laut einer Untersuchung schon erlebt — gemeldet wird sie selten, weil im hektischen Betrieb niemand einen langen Vorfallbericht schreibt. Das Restaurant Homeroom im kalifornischen Oakland führte deshalb ein dreistufiges Farbsystem ein: Gelb für unangenehme Blicke, Orange für anzügliche Bemerkungen, Rot für explizite Sprüche oder Berührungen. Je nach Farbe reagiert die Leitung gestaffelt, vom Tischwechsel bis zum Hausverbot. Das ist strukturell wichtig, weil es die Beweislast von den Betroffenen nimmt — sie nennen eine Farbe, nicht eine Rechtfertigung.', 'gemeinschaft', 'Vereinigte Staaten', 'US', 37.8044, -122.2712, NULL, 'https://reasonstobecheerful.world/yellow-means-creepy-the-color-coded-anti-harassment-system-used-by-restaurant-workers/', 'Reasons to be Cheerful', 100000, 65, 70, 58, 2, '2026-06-26T08:00:41+00:00', NULL, NULL, NULL, 'pride', 70, false, NULL, false, NULL, NULL, NULL, NULL, false, 45, 'Statt sich zu rechtfertigen, sagen Beschäftigte nur eine Farbe — und die Reaktion steht vorher fest.', 'Gelb, Orange, Rot: Ein Restaurant hat Belästigung durch Gäste zu einem Farb-Code gemacht. Seitdem muss niemand mehr erklären, ob es „schlimm genug“ war.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://reasonstobecheerful.world/yellow-means-creepy-the-color-coded-anti-harassment-system-used-by-restaurant-workers/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'In der trockensten Wüste der Welt ernten Dörfer Nebel', 'Netze fangen die Wolken, die vom Pazifik landeinwärts ziehen — und liefern Trinkwasser, wo Tanklaster zu teuer sind.', 'Es gibt Orte in Chiles Atacama-Wüste, an denen noch nie Niederschlag gemessen wurde. In anderen fällt Regen ein paar Mal pro Jahrhundert. Sie zählt zu den trockensten Regionen der Erde.

Für die Menschen, die dort leben, bedeutet das eine tägliche Logistikaufgabe. In vielen ländlichen Gemeinden muss die Kommune Wasser aus anderen Landesteilen mit Lastwagen heranschaffen oder aus tiefen Brunnen fördern. In schwerer erreichbaren Siedlungen ist beides weder kosteneffizient noch verlässlich.

Deshalb haben Bewohnerinnen und Forschende nach Wegen gesucht, Wasser direkt aus der Umgebung zu holen — und sind bei etwas gelandet, das ohnehin regelmäßig vorbeizieht: dem **Nebel**, der weite Teile Nordchiles einhüllt.

Die Mechanik dahinter ist geografisch bedingt. Vor der Pazifikküste kühlen kalte Meeresströmungen die Luft ab, sodass sich niedrige Wolken bilden. Diese ziehen landeinwärts, werden von den Küstenbergen gestoppt und legen sich dort auf Bodenhöhe.

„Ganz einfach gesagt müssen wir verstehen, dass Wolken aus Wassertröpfchen bestehen“, sagt Camilo del Río, Direktor des Atacama-Wüstenzentrums der Katholischen Universität in Chile. „Sie sind bereits gebildet, bereits kondensiert. Wann immer also eine Wolke vom Wind transportiert wird und mit der Erdoberfläche in Kontakt kommt, sind das Tausende und Abertausende Liter, die die Oberfläche berühren.“

Genau darin liegt der Reiz des Verfahrens, das im Englischen *fog harvesting* heißt — Nebelernte. Anders als bei der Entsalzung von Meerwasser muss keine Energie aufgewendet werden, um Wasser aus etwas anderem zu lösen. Das Wasser ist bereits Wasser. Es muss nur aufgefangen werden.

In der Praxis geschieht das mit fein gewebten Netzen, die senkrecht im Wind stehen. Die Tröpfchen schlagen sich am Gewebe nieder, laufen zusammen und tropfen in Rinnen und Tanks.

Lokale Gruppen gewinnen auf diese Weise inzwischen genug Nebelwasser, um ihre Trinkwasserversorgung zu ergänzen und landwirtschaftliche Projekte zu stützen.

Es bleiben allerdings erhebliche Herausforderungen. Forschende arbeiten daran, den Nebel effizienter zu ernten — denn die Ausbeute hängt von Windrichtung, Netzmaterial und Standort ab, und nicht jeder Ort in der Wüste liegt dort, wo die Wolken auf die Berge treffen.

Eine flächendeckende Lösung für die Wasserknappheit ist es damit nicht. Für Siedlungen, zu denen kein Tanklaster fährt, ist es der Unterschied zwischen abhängig und versorgt.', 'Die Atacama-Wüste in Chile gehört zu den trockensten Orten der Erde: In manchen Gebieten regnet es nur wenige Male pro Jahrhundert, in anderen wurde noch nie Regen gemessen. Weil Wasser bislang mit Lastwagen herangefahren oder aus tiefen Brunnen geholt werden muss, was für abgelegene Siedlungen zu teuer und unzuverlässig ist, fangen Bewohner und Forschende dort inzwischen den Nebel selbst ein — kalte Luftströme vom Pazifik bilden niedrige Wolken, die an den Küstenbergen hängen bleiben. Mit geeigneten Netzen lässt sich daraus nutzbares Süßwasser gewinnen, das Trinkwasser ergänzt und Landwirtschaft ermöglicht. Wie weit sich die Methode ausbauen lässt, erforschen die Beteiligten noch.', 'klima', 'Chile', 'CL', -23.8628, -69.1295, NULL, 'https://news.mongabay.com/2026/07/can-fog-harvesting-help-solve-water-scarcity-in-chiles-atacama-desert/', 'Mongabay', 30000, 70, 70, 55, 2, '2026-07-17T20:09:16+00:00', 7, 'Nebel ist eine Wolke, die den Boden berührt — und Wolken bestehen aus winzigen Wassertropfen.', 'Wo könnte man bei uns Wasser auffangen, das sonst einfach verschwindet?', 'wonder', 60, false, NULL, false, NULL, NULL, NULL, NULL, false, 35, 'Wo nie Regen fällt, hängen trotzdem Wolken — Netze machen daraus Trinkwasser ohne Tanklaster.', 'In der trockensten Wüste der Welt spannen Dörfer Netze auf und ernten den Nebel. Das Wasser ist schon da — es muss nur aufgefangen werden.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://news.mongabay.com/2026/07/can-fog-harvesting-help-solve-water-scarcity-in-chiles-atacama-desert/');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Plastikflaschen am Fischernetz retten fast 90 % der Delfine', 'An Stellnetze gebundene Flaschen senkten die Zahl getöteter Delfine um knapp 90 Prozent — ohne dass der Fang zurückging.', 'Der Konflikt zwischen Fischerei und Meeressäugern gilt als eines der zähesten Naturschutzprobleme überhaupt — weil jede Lösung, die den Fang schmälert, in der Praxis scheitert.

Stellnetze hängen wie fast unsichtbare Wände im Wasser. Fische schwimmen hinein und verfangen sich. Das Problem: Delfine tun das ebenfalls. Als Säugetiere müssen sie zum Atmen an die Oberfläche — verheddern sie sich, ertrinken sie. Fachleute sprechen von **Beifang**, also von Tieren, die ungewollt mitgefangen werden.

Eine neue Studie zeigt nun einen verblüffend simplen Ansatz: An die Netze gebundene **Plastikflaschen** senkten die Zahl der getöteten Delfine um **fast 90 Prozent**.

Der entscheidende Befund steckt jedoch im Nebensatz: Der Fischfang ging dabei **nicht zurück**. Genau daran sind viele Schutzmaßnahmen bisher gescheitert — wer weniger fängt, macht nicht mit.

Warum das funktioniert, hat mit der Art zu tun, wie Delfine ihre Umwelt wahrnehmen. Sie orientieren sich per Echoortung, senden also Klicklaute aus und lesen aus dem Echo, was vor ihnen liegt. Ein feines Netz wirft kaum ein Echo zurück. Eine harte, hohle Plastikflasche dagegen schon — sie macht die Netzwand für die Tiere hörbar.

Der Reiz der Methode liegt in ihrer Anspruchslosigkeit. Es braucht keine Elektronik, keine Batterien, keine Wartung und keine Förderprogramme — nur leere Flaschen, die ohnehin überall herumliegen. Damit ist sie auch für Küstenfischerei in Ländern verfügbar, in denen akustische Warngeräte schlicht unbezahlbar sind.

Es ist die seltene Art von Naturschutz, bei der niemand etwas aufgeben muss. Die Delfine hören das Netz. Die Fischer behalten ihren Fang.', 'Stellnetze sind fast unsichtbare Netzwände im Wasser, in denen sich regelmäßig auch Delfine verfangen und ertrinken — Fachleute nennen das Beifang, also ungewollt mitgefangene Tiere. Eine neue Studie zeigt, dass sich dieses Problem mit etwas erstaunlich Einfachem entschärfen lässt: Bindet man leere Plastikflaschen an die Netze, sinkt die Zahl getöteter Delfine um fast 90 Prozent. Entscheidend ist, dass der Fischfang darunter nicht leidet — der Fang blieb gleich. Das macht die Methode auch für Fischer attraktiv, die sich teure Technik nicht leisten können oder wollen.', 'tiere', 'Global', 'INT', 0.0, 0.0, NULL, 'https://www.anthropocenemagazine.org/2026/07/recycling-that-rescues-dolphins/?utm_source=rss&utm_medium=rss&utm_campaign=recycling-that-rescues-dolphins', 'Anthropocene Magazine', 50000, 70, 80, 64, 1, '2026-07-08T12:00:00+00:00', 7, 'Delfine finden sich unter Wasser mit Geräuschen zurecht — wie eine Fledermaus in der Luft.', 'Was könnte man noch mit Sachen lösen, die eigentlich Müll sind?', 'wonder', 60, false, NULL, false, NULL, NULL, NULL, NULL, false, 40, 'Leere Plastikflaschen am Netz — und fast 90 % weniger Delfine sterben, ohne dass Fischer weniger fangen.', 'Leere Plastikflaschen ans Fischernetz binden. Ergebnis: fast 90 % weniger tote Delfine — und der Fang bleibt gleich.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.anthropocenemagazine.org/2026/07/recycling-that-rescues-dolphins/?utm_source=rss&utm_medium=rss&utm_campaign=recycling-that-rescues-dolphins');

INSERT INTO nureine_stories (title, subtitle, body_markdown, summary, category, region, region_code, lat, lng, image_url, source_url, source_name, impact_reach, impact_durability, impact_evidence, impact_score, reading_time_min, published_at, kid_min_age, kid_explainer, conversation_starter, emotion, dach_relevanz, ig_ok, ig_hook_type, wa_ok, ig_hook, wa_opener, slides, ig_caption, sensitive, impact_reach_score, impact_explainer, share_hook)
SELECT 'Bis zu 45 % des Demenz-Risikos lassen sich selbst senken', 'Neue Leitlinien der Weltgesundheitsorganisation: 45 % des Demenz-Risikos hängen an beeinflussbaren Faktoren wie Blutdruck, Rauchen und Einsamkeit.', 'Demenz gehört zu den Krankheiten, vor denen Menschen sich am meisten fürchten — und lange galt sie als etwas, das einen entweder trifft oder nicht. Die Weltgesundheitsorganisation hat nun aktualisierte Leitlinien zur Senkung des Demenz-Risikos veröffentlicht, die dieses Bild deutlich verschieben.

Weltweit leben mehr als **57 Millionen Menschen** mit einer Demenz, fast **10 Millionen** kommen jährlich neu dazu. Die Alzheimer-Krankheit, die häufigste Form, macht dabei nach Schätzungen 60 bis 70 Prozent der Fälle aus. Eine Heilung gibt es bis heute nicht.

Umso schwerer wiegt die zentrale Zahl der neuen Leitlinien: Bis zu **45 Prozent** des Demenz-Risikos lassen sich auf sogenannte modifizierbare Risikofaktoren zurückführen — also auf Umstände, die veränderbar sind. Dazu zählt die Weltgesundheitsorganisation Tabak- und Alkoholkonsum, soziale Isolation, körperliche Inaktivität, Luftverschmutzung sowie nicht übertragbare Krankheiten wie Bluthochdruck und Diabetes.

„Wir wissen heute mehr denn je darüber, was das Demenz-Risiko antreibt, und diese Leitlinien übersetzen dieses Wissen in Handeln“, sagte Tedros Adhanom Ghebreyesus, Generaldirektor der Weltgesundheitsorganisation. Länder hätten nun klare, evidenzbasierte Empfehlungen, die sie unmittelbar umsetzen könnten.

Die Empfehlungen sind eine Fortschreibung: Erstmals hatte die Organisation 2019 Leitlinien zur Demenz-Vorbeugung herausgegeben. Seither ist die Studienlage erheblich gewachsen. Die neue Fassung bündelt Empfehlungen zu ungesunden Verhaltensweisen, zur Behandlung bestehender Erkrankungen und zur Verringerung von Umweltbelastungen.

Zu den empfohlenen Maßnahmen gehören unter anderem kognitives Training und geistige Anregung — also gezieltes Fordern des Denkvermögens — neben Bewegung und der konsequenten Behandlung von Bluthochdruck.

Der eigentliche Hebel liegt jedoch nicht beim Einzelnen allein. Luftverschmutzung und soziale Isolation sind Faktoren, die sich kaum privat wegtrainieren lassen; sie sind Ergebnis von Verkehrs-, Stadt- und Sozialpolitik. Genau deshalb richten sich die Leitlinien an Regierungen und Gesundheitssysteme, nicht an Patientinnen und Patienten.

Die Weltgesundheitsorganisation sieht darin die Chance, die Krankheitslast durch Demenz in den kommenden Jahrzehnten spürbar zu senken — durch eine engere Verzahnung der Versorgung bei nicht übertragbaren Krankheiten, psychischer Gesundheit und Hirngesundheit.

Für Menschen mit Angehörigen, die an Demenz erkrankt sind, ändert das nichts an der Gegenwart. Für alle anderen verschiebt es etwas Grundlegendes: Ein erheblicher Teil des Risikos ist kein Schicksal.', 'Demenz ist ein Sammelbegriff für Krankheiten, die Gedächtnis und Denkvermögen zerstören — weltweit leben über 57 Millionen Menschen damit, jedes Jahr kommen fast 10 Millionen neue Diagnosen dazu. Die Weltgesundheitsorganisation hat jetzt neue Leitlinien vorgelegt, nach denen sich bis zu 45 Prozent des Erkrankungsrisikos auf Faktoren zurückführen lassen, die man ändern kann: Rauchen, Alkohol, Bewegungsmangel, soziale Isolation, Luftverschmutzung, hoher Blutdruck und Diabetes. Das ist strukturell bedeutsam, weil es Demenz vom unabwendbaren Schicksal zu einer teilweise vermeidbaren Krankheit macht — und Ländern konkrete Maßnahmen an die Hand gibt. Weil es bis heute keine Heilung gibt, ist Vorbeugung derzeit der wirksamste Hebel, den Gesellschaften überhaupt haben.', 'gesundheit', 'Global', 'INT', 46.2324, 6.1357, NULL, 'https://www.who.int/news/item/15-07-2026-new-who-guidelines--up-to-45--of-dementia-risk-could-be-prevented-or-delayed', 'WHO News', 57000000, 90, 95, 82, 2, 'Wed, 15 Jul 2026 12:15:58 Z', 10, 'Demenz ist eine Krankheit im Gehirn, bei der Menschen nach und nach vergessen, was sie erlebt haben.', 'Was glaubst du, hilft dem Gehirn mehr: viel lernen oder viele Freunde haben?', 'hope', 85, true, 'zahl', false, '45 % des Demenz-Risikos sind kein Schicksal.', NULL, '{"hook": "45 % des Demenz-Risikos sind kein Schicksal.", "aufloesung": "Die Weltgesundheitsorganisation hat neue Leitlinien vorgelegt. Bis zu 45 Prozent des Risikos hängen an Faktoren, die veränderbar sind: Blutdruck, Rauchen, Alkohol, Bewegungsmangel, Luftverschmutzung — und soziale Isolation. Eine Heilung gibt es weiter nicht. Vorbeugung ist aber wirksamer als gedacht.", "stille": "Manches, wovor wir uns fürchten, ist beeinflussbarer als wir dachten."}'::jsonb, 'Kaum eine Krankheit macht so viel Angst wie diese — weil sie sich anfühlt wie ein Los, das man zieht.
Die Weltgesundheitsorganisation hat jetzt nachgerechnet. 👇

Quelle: WHO News', false, 90, 'Fast die Hälfte des Demenz-Risikos hängt an Dingen, die sich ändern lassen — Blutdruck, Rauchen, Einsamkeit.', 'Die Weltgesundheitsorganisation sagt: Bis zu 45 % des Demenz-Risikos hängen an Faktoren, die man beeinflussen kann. Nicht alles ist Schicksal.'
WHERE NOT EXISTS (SELECT 1 FROM nureine_stories WHERE source_url = 'https://www.who.int/news/item/15-07-2026-new-who-guidelines--up-to-45--of-dementia-risk-could-be-prevented-or-delayed');

